// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: accelerator_orchestrator.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// State defines the possible states of a group lock.
type GroupStatus_State int32

const (
	// STATE_UNSPECIFIED is the default unspecified state.
	GroupStatus_STATE_UNSPECIFIED GroupStatus_State = 0
	// STATE_UNKNOWN indicates the state cannot be determined (e.g. agents unreachable).
	GroupStatus_STATE_UNKNOWN GroupStatus_State = 1
	// STATE_IDLE indicates the group is unlocked and has no yielded job.
	GroupStatus_STATE_IDLE GroupStatus_State = 2
	// STATE_IDLE_YIELDED indicates the group lock is free but the context is still active (yielded).
	GroupStatus_STATE_IDLE_YIELDED GroupStatus_State = 3
	// STATE_LOCKED indicates a job holds the lock and has not yielded.
	GroupStatus_STATE_LOCKED GroupStatus_State = 4
	// STATE_SWITCHING indicates a transition is in progress.
	GroupStatus_STATE_SWITCHING GroupStatus_State = 5
)

// Enum value maps for GroupStatus_State.
var (
	GroupStatus_State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "STATE_UNKNOWN",
		2: "STATE_IDLE",
		3: "STATE_IDLE_YIELDED",
		4: "STATE_LOCKED",
		5: "STATE_SWITCHING",
	}
	GroupStatus_State_value = map[string]int32{
		"STATE_UNSPECIFIED":  0,
		"STATE_UNKNOWN":      1,
		"STATE_IDLE":         2,
		"STATE_IDLE_YIELDED": 3,
		"STATE_LOCKED":       4,
		"STATE_SWITCHING":    5,
	}
)

func (x GroupStatus_State) Enum() *GroupStatus_State {
	p := new(GroupStatus_State)
	*p = x
	return p
}

func (x GroupStatus_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GroupStatus_State) Descriptor() protoreflect.EnumDescriptor {
	return file_accelerator_orchestrator_proto_enumTypes[0].Descriptor()
}

func (GroupStatus_State) Type() protoreflect.EnumType {
	return &file_accelerator_orchestrator_proto_enumTypes[0]
}

func (x GroupStatus_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GroupStatus_State.Descriptor instead.
func (GroupStatus_State) EnumDescriptor() ([]byte, []int) {
	return file_accelerator_orchestrator_proto_rawDescGZIP(), []int{8, 0}
}

// State defines the possible states of a job's accelerator context.
type SnapshotAgentJobState_State int32

const (
	// STATE_UNSPECIFIED is the default unspecified state.
	SnapshotAgentJobState_STATE_UNSPECIFIED SnapshotAgentJobState_State = 0
	// STATE_IDLE indicates the job is known but has no accelerator context yet.
	SnapshotAgentJobState_STATE_IDLE SnapshotAgentJobState_State = 1
	// STATE_RUNNING indicates the job's context is active on the accelerator.
	SnapshotAgentJobState_STATE_RUNNING SnapshotAgentJobState_State = 2
	// STATE_TRANSITIONING indicates a snapshot or restore operation is in progress.
	SnapshotAgentJobState_STATE_TRANSITIONING SnapshotAgentJobState_State = 3
	// STATE_SAVED indicates the context is saved to host memory and device memory is freed.
	SnapshotAgentJobState_STATE_SAVED SnapshotAgentJobState_State = 4
	// STATE_FAULTED indicates the last operation failed and requires operator intervention.
	SnapshotAgentJobState_STATE_FAULTED SnapshotAgentJobState_State = 5
)

// Enum value maps for SnapshotAgentJobState_State.
var (
	SnapshotAgentJobState_State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "STATE_IDLE",
		2: "STATE_RUNNING",
		3: "STATE_TRANSITIONING",
		4: "STATE_SAVED",
		5: "STATE_FAULTED",
	}
	SnapshotAgentJobState_State_value = map[string]int32{
		"STATE_UNSPECIFIED":   0,
		"STATE_IDLE":          1,
		"STATE_RUNNING":       2,
		"STATE_TRANSITIONING": 3,
		"STATE_SAVED":         4,
		"STATE_FAULTED":       5,
	}
)

func (x SnapshotAgentJobState_State) Enum() *SnapshotAgentJobState_State {
	p := new(SnapshotAgentJobState_State)
	*p = x
	return p
}

func (x SnapshotAgentJobState_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SnapshotAgentJobState_State) Descriptor() protoreflect.EnumDescriptor {
	return file_accelerator_orchestrator_proto_enumTypes[1].Descriptor()
}

func (SnapshotAgentJobState_State) Type() protoreflect.EnumType {
	return &file_accelerator_orchestrator_proto_enumTypes[1]
}

func (x SnapshotAgentJobState_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SnapshotAgentJobState_State.Descriptor instead.
func (SnapshotAgentJobState_State) EnumDescriptor() ([]byte, []int) {
	return file_accelerator_orchestrator_proto_rawDescGZIP(), []int{9, 0}
}

// AcquireRequest is the request to acquire exclusive access to a group.
type AcquireRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// job_id is the unique identifier of the job requesting access.
	// Must match the timeslice.io/job-id annotation on the pod.
	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// group_id is the unique identifier of the time-slice group.
	// Must match the timeslice.io/group annotation on the pod.
	GroupId       string `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquireRequest) Reset() {
	*x = AcquireRequest{}
	mi := &file_accelerator_orchestrator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireRequest) ProtoMessage() {}

func (x *AcquireRequest) ProtoReflect() protoreflect.Message {
	mi := &file_accelerator_orchestrator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireRequest.ProtoReflect.Descriptor instead.
func (*AcquireRequest) Descriptor() ([]byte, []int) {
	return file_accelerator_orchestrator_proto_rawDescGZIP(), []int{0}
}

func (x *AcquireRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *AcquireRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

// AcquireResponse is the response after acquiring access.
type AcquireResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// success indicates whether the acquisition was successful.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// waited_ms is the duration in milliseconds the job spent waiting in the queue.
	WaitedMs int64 `protobuf:"varint,2,opt,name=waited_ms,json=waitedMs,proto3" json:"waited_ms,omitempty"`
	// context_restored indicates whether the job's accelerator context was physically
	// restored from host memory. If false, it means the context was already live (e.g., zero-overhead path).
	ContextRestored bool `protobuf:"varint,3,opt,name=context_restored,json=contextRestored,proto3" json:"context_restored,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AcquireResponse) Reset() {
	*x = AcquireResponse{}
	mi := &file_accelerator_orchestrator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireResponse) ProtoMessage() {}

func (x *AcquireResponse) ProtoReflect() protoreflect.Message {
	mi := &file_accelerator_orchestrator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireResponse.ProtoReflect.Descriptor instead.
func (*AcquireResponse) Descriptor() ([]byte, []int) {
	return file_accelerator_orchestrator_proto_rawDescGZIP(), []int{1}
}

func (x *AcquireResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AcquireResponse) GetWaitedMs() int64 {
	if x != nil {
		return x.WaitedMs
	}
	return 0
}

func (x *AcquireResponse) GetContextRestored() bool {
	if x != nil {
		return x.ContextRestored
	}
	return false
}

// YieldRequest is the request to release access to a group.
type YieldRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// job_id is the unique identifier of the job yielding access.
	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// group_id is the unique identifier of the time-slice group being yielded.
	GroupId       string `protobuf:"bytes,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *YieldRequest) Reset() {
	*x = YieldRequest{}
	mi := &file_accelerator_orchestrator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YieldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YieldRequest) ProtoMessage() {}

func (x *YieldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_accelerator_orchestrator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YieldRequest.ProtoReflect.Descriptor instead.
func (*YieldRequest) Descriptor() ([]byte, []int) {
	return file_accelerator_orchestrator_proto_rawDescGZIP(), []int{2}
}

func (x *YieldRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *YieldRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

// YieldResponse is the response after yielding access.
type YieldResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// success indicates whether the yield was successful.
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// pending_waiters is the number of jobs currently waiting in the queue for this group.
	PendingWaiters int64 `protobuf:"varint,2,opt,name=pending_waiters,json=pendingWaiters,proto3" json:"pending_waiters,omitempty"`
	// snapshot_deferred indicates whether the physical snapshot was skipped because
	// there were no waiting jobs in the queue.
	SnapshotDeferred bool `protobuf:"varint,3,opt,name=snapshot_deferred,json=snapshotDeferred,proto3" json:"snapshot_deferred,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *YieldResponse) Reset() {
	*x = YieldResponse{}
	mi := &file_accelerator_orchestrator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *YieldResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*YieldResponse) ProtoMessage() {}

func (x *YieldResponse) ProtoReflect() protoreflect.Message {
	mi := &file_accelerator_orchestrator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use YieldResponse.ProtoReflect.Descriptor instead.
func (*YieldResponse) Descriptor() ([]byte, []int) {
	return file_accelerator_orchestrator_proto_rawDescGZIP(), []int{3}
}

func (x *YieldResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *YieldResponse) GetPendingWaiters() int64 {
	if x != nil {
		return x.PendingWaiters
	}
	return 0
}

func (x *YieldResponse) GetSnapshotDeferred() bool {
	if x != nil {
		return x.SnapshotDeferred
	}
	return false
}

// ListGroupsRequest is the request to list active groups.
type ListGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupsRequest) Reset() {
	*x = ListGroupsRequest{}
	mi := &file_accelerator_orchestrator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupsRequest) ProtoMessage() {}

func (x *ListGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_accelerator_orchestrator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupsRequest.ProtoReflect.Descriptor instead.
func (*ListGroupsRequest) Descriptor() ([]byte, []int) {
	return file_accelerator_orchestrator_proto_rawDescGZIP(), []int{4}
}

// ListGroupsResponse is the response containing active groups.
type ListGroupsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// group_ids is a list of all active time-slice group IDs.
	GroupIds      []string `protobuf:"bytes,1,rep,name=group_ids,json=groupIds,proto3" json:"group_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupsResponse) Reset() {
	*x = ListGroupsResponse{}
	mi := &file_accelerator_orchestrator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupsResponse) ProtoMessage() {}

func (x *ListGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_accelerator_orchestrator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupsResponse.ProtoReflect.Descriptor instead.
func (*ListGroupsResponse) Descriptor() ([]byte, []int) {
	return file_accelerator_orchestrator_proto_rawDescGZIP(), []int{5}
}

func (x *ListGroupsResponse) GetGroupIds() []string {
	if x != nil {
		return x.GroupIds
	}
	return nil
}

// GetGroupStatusRequest is the request to get status of a group.
type GetGroupStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// group_id is the unique identifier of the group to query.
	GroupId       string `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGroupStatusRequest) Reset() {
	*x = GetGroupStatusRequest{}
	mi := &file_accelerator_orchestrator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupStatusRequest) ProtoMessage() {}

func (x *GetGroupStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_accelerator_orchestrator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupStatusRequest.ProtoReflect.Descriptor instead.
func (*GetGroupStatusRequest) Descriptor() ([]byte, []int) {
	return file_accelerator_orchestrator_proto_rawDescGZIP(), []int{6}
}

func (x *GetGroupStatusRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

// GetGroupStatusResponse is the response containing group status.
type GetGroupStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// group contains the high-level status of the group (locking_job, queue depth).
	Group *GroupStatus `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	// agent_job_states contains the detailed state of this job across all
	// node-local snapshot agents participating in the group.
	AgentJobStates []*SnapshotAgentJobState `protobuf:"bytes,2,rep,name=agent_job_states,json=agentJobStates,proto3" json:"agent_job_states,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetGroupStatusResponse) Reset() {
	*x = GetGroupStatusResponse{}
	mi := &file_accelerator_orchestrator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGroupStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGroupStatusResponse) ProtoMessage() {}

func (x *GetGroupStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_accelerator_orchestrator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGroupStatusResponse.ProtoReflect.Descriptor instead.
func (*GetGroupStatusResponse) Descriptor() ([]byte, []int) {
	return file_accelerator_orchestrator_proto_rawDescGZIP(), []int{7}
}

func (x *GetGroupStatusResponse) GetGroup() *GroupStatus {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *GetGroupStatusResponse) GetAgentJobStates() []*SnapshotAgentJobState {
	if x != nil {
		return x.AgentJobStates
	}
	return nil
}

// GroupStatus represents the high-level status of a time-slice group lock.
type GroupStatus struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// group_id is the unique identifier of the group.
	GroupId string `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	// group_state is the current state of the group lock.
	GroupState GroupStatus_State `protobuf:"varint,2,opt,name=group_state,json=groupState,proto3,enum=accelerator_orchestrator.v1alpha1.GroupStatus_State" json:"group_state,omitempty"`
	// state_timestamp is the time when the orchestrator entered the current state.
	StateTimestamp *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=state_timestamp,json=stateTimestamp,proto3" json:"state_timestamp,omitempty"`
	// locking_job is the job_id of the job currently holding the group lock.
	// Empty if the group is currently idle (unlocked).
	LockingJob string `protobuf:"bytes,4,opt,name=locking_job,json=lockingJob,proto3" json:"locking_job,omitempty"`
	// active_job is the job_id of the job whose context is currently active on the accelerators in the group.
	// Empty if no job context is active.
	ActiveJob string `protobuf:"bytes,5,opt,name=active_job,json=activeJob,proto3" json:"active_job,omitempty"`
	// waiter_queue_depth is the number of jobs currently waiting in the queue.
	WaiterQueueDepth int64 `protobuf:"varint,6,opt,name=waiter_queue_depth,json=waiterQueueDepth,proto3" json:"waiter_queue_depth,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GroupStatus) Reset() {
	*x = GroupStatus{}
	mi := &file_accelerator_orchestrator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupStatus) ProtoMessage() {}

func (x *GroupStatus) ProtoReflect() protoreflect.Message {
	mi := &file_accelerator_orchestrator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupStatus.ProtoReflect.Descriptor instead.
func (*GroupStatus) Descriptor() ([]byte, []int) {
	return file_accelerator_orchestrator_proto_rawDescGZIP(), []int{8}
}

func (x *GroupStatus) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GroupStatus) GetGroupState() GroupStatus_State {
	if x != nil {
		return x.GroupState
	}
	return GroupStatus_STATE_UNSPECIFIED
}

func (x *GroupStatus) GetStateTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.StateTimestamp
	}
	return nil
}

func (x *GroupStatus) GetLockingJob() string {
	if x != nil {
		return x.LockingJob
	}
	return ""
}

func (x *GroupStatus) GetActiveJob() string {
	if x != nil {
		return x.ActiveJob
	}
	return ""
}

func (x *GroupStatus) GetWaiterQueueDepth() int64 {
	if x != nil {
		return x.WaiterQueueDepth
	}
	return 0
}

// SnapshotAgentJobState represents the state of a job's accelerator context
// on a specific node-local Snapshot Agent.
type SnapshotAgentJobState struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// agent is the identifier of the Snapshot Agent (typically the node name).
	Agent string `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	// job_state is the current state of the job's context on this agent.
	JobState      SnapshotAgentJobState_State `protobuf:"varint,2,opt,name=job_state,json=jobState,proto3,enum=accelerator_orchestrator.v1alpha1.SnapshotAgentJobState_State" json:"job_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotAgentJobState) Reset() {
	*x = SnapshotAgentJobState{}
	mi := &file_accelerator_orchestrator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotAgentJobState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotAgentJobState) ProtoMessage() {}

func (x *SnapshotAgentJobState) ProtoReflect() protoreflect.Message {
	mi := &file_accelerator_orchestrator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotAgentJobState.ProtoReflect.Descriptor instead.
func (*SnapshotAgentJobState) Descriptor() ([]byte, []int) {
	return file_accelerator_orchestrator_proto_rawDescGZIP(), []int{9}
}

func (x *SnapshotAgentJobState) GetAgent() string {
	if x != nil {
		return x.Agent
	}
	return ""
}

func (x *SnapshotAgentJobState) GetJobState() SnapshotAgentJobState_State {
	if x != nil {
		return x.JobState
	}
	return SnapshotAgentJobState_STATE_UNSPECIFIED
}

var File_accelerator_orchestrator_proto protoreflect.FileDescriptor

const file_accelerator_orchestrator_proto_rawDesc = "" +
	"\n" +
	"\x1eaccelerator_orchestrator.proto\x12!accelerator_orchestrator.v1alpha1\x1a\x1fgoogle/protobuf/timestamp.proto\"B\n" +
	"\x0eAcquireRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\"s\n" +
	"\x0fAcquireResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\twaited_ms\x18\x02 \x01(\x03R\bwaitedMs\x12)\n" +
	"\x10context_restored\x18\x03 \x01(\bR\x0fcontextRestored\"@\n" +
	"\fYieldRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x19\n" +
	"\bgroup_id\x18\x02 \x01(\tR\agroupId\"\x7f\n" +
	"\rYieldResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12'\n" +
	"\x0fpending_waiters\x18\x02 \x01(\x03R\x0ependingWaiters\x12+\n" +
	"\x11snapshot_deferred\x18\x03 \x01(\bR\x10snapshotDeferred\"\x13\n" +
	"\x11ListGroupsRequest\"1\n" +
	"\x12ListGroupsResponse\x12\x1b\n" +
	"\tgroup_ids\x18\x01 \x03(\tR\bgroupIds\"2\n" +
	"\x15GetGroupStatusRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\"\xc2\x01\n" +
	"\x16GetGroupStatusResponse\x12D\n" +
	"\x05group\x18\x01 \x01(\v2..accelerator_orchestrator.v1alpha1.GroupStatusR\x05group\x12b\n" +
	"\x10agent_job_states\x18\x02 \x03(\v28.accelerator_orchestrator.v1alpha1.SnapshotAgentJobStateR\x0eagentJobStates\"\xb5\x03\n" +
	"\vGroupStatus\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12U\n" +
	"\vgroup_state\x18\x02 \x01(\x0e24.accelerator_orchestrator.v1alpha1.GroupStatus.StateR\n" +
	"groupState\x12C\n" +
	"\x0fstate_timestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x0estateTimestamp\x12\x1f\n" +
	"\vlocking_job\x18\x04 \x01(\tR\n" +
	"lockingJob\x12\x1d\n" +
	"\n" +
	"active_job\x18\x05 \x01(\tR\tactiveJob\x12,\n" +
	"\x12waiter_queue_depth\x18\x06 \x01(\x03R\x10waiterQueueDepth\"\x80\x01\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSTATE_UNKNOWN\x10\x01\x12\x0e\n" +
	"\n" +
	"STATE_IDLE\x10\x02\x12\x16\n" +
	"\x12STATE_IDLE_YIELDED\x10\x03\x12\x10\n" +
	"\fSTATE_LOCKED\x10\x04\x12\x13\n" +
	"\x0fSTATE_SWITCHING\x10\x05\"\x8a\x02\n" +
	"\x15SnapshotAgentJobState\x12\x14\n" +
	"\x05agent\x18\x01 \x01(\tR\x05agent\x12[\n" +
	"\tjob_state\x18\x02 \x01(\x0e2>.accelerator_orchestrator.v1alpha1.SnapshotAgentJobState.StateR\bjobState\"~\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"STATE_IDLE\x10\x01\x12\x11\n" +
	"\rSTATE_RUNNING\x10\x02\x12\x17\n" +
	"\x13STATE_TRANSITIONING\x10\x03\x12\x0f\n" +
	"\vSTATE_SAVED\x10\x04\x12\x11\n" +
	"\rSTATE_FAULTED\x10\x052\x81\x04\n" +
	"\x1eAcceleratorOrchestratorService\x12p\n" +
	"\aAcquire\x121.accelerator_orchestrator.v1alpha1.AcquireRequest\x1a2.accelerator_orchestrator.v1alpha1.AcquireResponse\x12j\n" +
	"\x05Yield\x12/.accelerator_orchestrator.v1alpha1.YieldRequest\x1a0.accelerator_orchestrator.v1alpha1.YieldResponse\x12y\n" +
	"\n" +
	"ListGroups\x124.accelerator_orchestrator.v1alpha1.ListGroupsRequest\x1a5.accelerator_orchestrator.v1alpha1.ListGroupsResponse\x12\x85\x01\n" +
	"\x0eGetGroupStatus\x128.accelerator_orchestrator.v1alpha1.GetGroupStatusRequest\x1a9.accelerator_orchestrator.v1alpha1.GetGroupStatusResponseBfZdgithub.com/llm-d-incubation/llm-d-rl-time-slicing/pkg/accelerator-orchestrator/api/v1alpha1;v1alpha1b\x06proto3"

var (
	file_accelerator_orchestrator_proto_rawDescOnce sync.Once
	file_accelerator_orchestrator_proto_rawDescData []byte
)

func file_accelerator_orchestrator_proto_rawDescGZIP() []byte {
	file_accelerator_orchestrator_proto_rawDescOnce.Do(func() {
		file_accelerator_orchestrator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_accelerator_orchestrator_proto_rawDesc), len(file_accelerator_orchestrator_proto_rawDesc)))
	})
	return file_accelerator_orchestrator_proto_rawDescData
}

var file_accelerator_orchestrator_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_accelerator_orchestrator_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_accelerator_orchestrator_proto_goTypes = []any{
	(GroupStatus_State)(0),           // 0: accelerator_orchestrator.v1alpha1.GroupStatus.State
	(SnapshotAgentJobState_State)(0), // 1: accelerator_orchestrator.v1alpha1.SnapshotAgentJobState.State
	(*AcquireRequest)(nil),           // 2: accelerator_orchestrator.v1alpha1.AcquireRequest
	(*AcquireResponse)(nil),          // 3: accelerator_orchestrator.v1alpha1.AcquireResponse
	(*YieldRequest)(nil),             // 4: accelerator_orchestrator.v1alpha1.YieldRequest
	(*YieldResponse)(nil),            // 5: accelerator_orchestrator.v1alpha1.YieldResponse
	(*ListGroupsRequest)(nil),        // 6: accelerator_orchestrator.v1alpha1.ListGroupsRequest
	(*ListGroupsResponse)(nil),       // 7: accelerator_orchestrator.v1alpha1.ListGroupsResponse
	(*GetGroupStatusRequest)(nil),    // 8: accelerator_orchestrator.v1alpha1.GetGroupStatusRequest
	(*GetGroupStatusResponse)(nil),   // 9: accelerator_orchestrator.v1alpha1.GetGroupStatusResponse
	(*GroupStatus)(nil),              // 10: accelerator_orchestrator.v1alpha1.GroupStatus
	(*SnapshotAgentJobState)(nil),    // 11: accelerator_orchestrator.v1alpha1.SnapshotAgentJobState
	(*timestamppb.Timestamp)(nil),    // 12: google.protobuf.Timestamp
}
var file_accelerator_orchestrator_proto_depIdxs = []int32{
	10, // 0: accelerator_orchestrator.v1alpha1.GetGroupStatusResponse.group:type_name -> accelerator_orchestrator.v1alpha1.GroupStatus
	11, // 1: accelerator_orchestrator.v1alpha1.GetGroupStatusResponse.agent_job_states:type_name -> accelerator_orchestrator.v1alpha1.SnapshotAgentJobState
	0,  // 2: accelerator_orchestrator.v1alpha1.GroupStatus.group_state:type_name -> accelerator_orchestrator.v1alpha1.GroupStatus.State
	12, // 3: accelerator_orchestrator.v1alpha1.GroupStatus.state_timestamp:type_name -> google.protobuf.Timestamp
	1,  // 4: accelerator_orchestrator.v1alpha1.SnapshotAgentJobState.job_state:type_name -> accelerator_orchestrator.v1alpha1.SnapshotAgentJobState.State
	2,  // 5: accelerator_orchestrator.v1alpha1.AcceleratorOrchestratorService.Acquire:input_type -> accelerator_orchestrator.v1alpha1.AcquireRequest
	4,  // 6: accelerator_orchestrator.v1alpha1.AcceleratorOrchestratorService.Yield:input_type -> accelerator_orchestrator.v1alpha1.YieldRequest
	6,  // 7: accelerator_orchestrator.v1alpha1.AcceleratorOrchestratorService.ListGroups:input_type -> accelerator_orchestrator.v1alpha1.ListGroupsRequest
	8,  // 8: accelerator_orchestrator.v1alpha1.AcceleratorOrchestratorService.GetGroupStatus:input_type -> accelerator_orchestrator.v1alpha1.GetGroupStatusRequest
	3,  // 9: accelerator_orchestrator.v1alpha1.AcceleratorOrchestratorService.Acquire:output_type -> accelerator_orchestrator.v1alpha1.AcquireResponse
	5,  // 10: accelerator_orchestrator.v1alpha1.AcceleratorOrchestratorService.Yield:output_type -> accelerator_orchestrator.v1alpha1.YieldResponse
	7,  // 11: accelerator_orchestrator.v1alpha1.AcceleratorOrchestratorService.ListGroups:output_type -> accelerator_orchestrator.v1alpha1.ListGroupsResponse
	9,  // 12: accelerator_orchestrator.v1alpha1.AcceleratorOrchestratorService.GetGroupStatus:output_type -> accelerator_orchestrator.v1alpha1.GetGroupStatusResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_accelerator_orchestrator_proto_init() }
func file_accelerator_orchestrator_proto_init() {
	if File_accelerator_orchestrator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_accelerator_orchestrator_proto_rawDesc), len(file_accelerator_orchestrator_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_accelerator_orchestrator_proto_goTypes,
		DependencyIndexes: file_accelerator_orchestrator_proto_depIdxs,
		EnumInfos:         file_accelerator_orchestrator_proto_enumTypes,
		MessageInfos:      file_accelerator_orchestrator_proto_msgTypes,
	}.Build()
	File_accelerator_orchestrator_proto = out.File
	file_accelerator_orchestrator_proto_goTypes = nil
	file_accelerator_orchestrator_proto_depIdxs = nil
}
