# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import snapshot_agent_pb2 as snapshot__agent__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in snapshot_agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SnapshotAgentServiceStub:
    """SnapshotAgentService provides APIs for managing accelerator snapshots.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Snapshot = channel.unary_unary(
                '/snapshot_agent.v1alpha1.SnapshotAgentService/Snapshot',
                request_serializer=snapshot__agent__pb2.SnapshotRequest.SerializeToString,
                response_deserializer=snapshot__agent__pb2.SnapshotResponse.FromString,
                _registered_method=True)
        self.Restore = channel.unary_unary(
                '/snapshot_agent.v1alpha1.SnapshotAgentService/Restore',
                request_serializer=snapshot__agent__pb2.RestoreRequest.SerializeToString,
                response_deserializer=snapshot__agent__pb2.RestoreResponse.FromString,
                _registered_method=True)
        self.GetOperation = channel.unary_unary(
                '/snapshot_agent.v1alpha1.SnapshotAgentService/GetOperation',
                request_serializer=snapshot__agent__pb2.GetOperationRequest.SerializeToString,
                response_deserializer=snapshot__agent__pb2.GetOperationResponse.FromString,
                _registered_method=True)
        self.Status = channel.unary_unary(
                '/snapshot_agent.v1alpha1.SnapshotAgentService/Status',
                request_serializer=snapshot__agent__pb2.StatusRequest.SerializeToString,
                response_deserializer=snapshot__agent__pb2.StatusResponse.FromString,
                _registered_method=True)


class SnapshotAgentServiceServicer:
    """SnapshotAgentService provides APIs for managing accelerator snapshots.
    """

    def Snapshot(self, request, context):
        """Snapshot triggers an asynchronous snapshot of the accelerator context for a job.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Restore(self, request, context):
        """Restore triggers an asynchronous restoration of the accelerator context for a job.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOperation(self, request, context):
        """GetOperation polls the status of a long-running snapshot or restore operation.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Status(self, request, context):
        """Status returns the current state of jobs and accelerators on the node.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SnapshotAgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Snapshot': grpc.unary_unary_rpc_method_handler(
                    servicer.Snapshot,
                    request_deserializer=snapshot__agent__pb2.SnapshotRequest.FromString,
                    response_serializer=snapshot__agent__pb2.SnapshotResponse.SerializeToString,
            ),
            'Restore': grpc.unary_unary_rpc_method_handler(
                    servicer.Restore,
                    request_deserializer=snapshot__agent__pb2.RestoreRequest.FromString,
                    response_serializer=snapshot__agent__pb2.RestoreResponse.SerializeToString,
            ),
            'GetOperation': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOperation,
                    request_deserializer=snapshot__agent__pb2.GetOperationRequest.FromString,
                    response_serializer=snapshot__agent__pb2.GetOperationResponse.SerializeToString,
            ),
            'Status': grpc.unary_unary_rpc_method_handler(
                    servicer.Status,
                    request_deserializer=snapshot__agent__pb2.StatusRequest.FromString,
                    response_serializer=snapshot__agent__pb2.StatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'snapshot_agent.v1alpha1.SnapshotAgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('snapshot_agent.v1alpha1.SnapshotAgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SnapshotAgentService:
    """SnapshotAgentService provides APIs for managing accelerator snapshots.
    """

    @staticmethod
    def Snapshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/snapshot_agent.v1alpha1.SnapshotAgentService/Snapshot',
            snapshot__agent__pb2.SnapshotRequest.SerializeToString,
            snapshot__agent__pb2.SnapshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Restore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/snapshot_agent.v1alpha1.SnapshotAgentService/Restore',
            snapshot__agent__pb2.RestoreRequest.SerializeToString,
            snapshot__agent__pb2.RestoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetOperation(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/snapshot_agent.v1alpha1.SnapshotAgentService/GetOperation',
            snapshot__agent__pb2.GetOperationRequest.SerializeToString,
            snapshot__agent__pb2.GetOperationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Status(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/snapshot_agent.v1alpha1.SnapshotAgentService/Status',
            snapshot__agent__pb2.StatusRequest.SerializeToString,
            snapshot__agent__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
