replicaCount: 1

image:
  repository: ghcr.io/llm-d/acceleratororchestrator
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 50051

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}
