// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: snapshot_agent.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Backend int32

const (
	Backend_BACKEND_UNSPECIFIED Backend = 0
	Backend_BACKEND_CUDA        Backend = 1
)

// Enum value maps for Backend.
var (
	Backend_name = map[int32]string{
		0: "BACKEND_UNSPECIFIED",
		1: "BACKEND_CUDA",
	}
	Backend_value = map[string]int32{
		"BACKEND_UNSPECIFIED": 0,
		"BACKEND_CUDA":        1,
	}
)

func (x Backend) Enum() *Backend {
	p := new(Backend)
	*p = x
	return p
}

func (x Backend) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Backend) Descriptor() protoreflect.EnumDescriptor {
	return file_snapshot_agent_proto_enumTypes[0].Descriptor()
}

func (Backend) Type() protoreflect.EnumType {
	return &file_snapshot_agent_proto_enumTypes[0]
}

func (x Backend) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Backend.Descriptor instead.
func (Backend) EnumDescriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{0}
}

type OperationStatus int32

const (
	OperationStatus_OPERATION_STATUS_UNSPECIFIED OperationStatus = 0
	OperationStatus_OPERATION_STATUS_PENDING     OperationStatus = 1
	OperationStatus_OPERATION_STATUS_COMPLETE    OperationStatus = 2
	OperationStatus_OPERATION_STATUS_FAILED      OperationStatus = 3
)

// Enum value maps for OperationStatus.
var (
	OperationStatus_name = map[int32]string{
		0: "OPERATION_STATUS_UNSPECIFIED",
		1: "OPERATION_STATUS_PENDING",
		2: "OPERATION_STATUS_COMPLETE",
		3: "OPERATION_STATUS_FAILED",
	}
	OperationStatus_value = map[string]int32{
		"OPERATION_STATUS_UNSPECIFIED": 0,
		"OPERATION_STATUS_PENDING":     1,
		"OPERATION_STATUS_COMPLETE":    2,
		"OPERATION_STATUS_FAILED":      3,
	}
)

func (x OperationStatus) Enum() *OperationStatus {
	p := new(OperationStatus)
	*p = x
	return p
}

func (x OperationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_snapshot_agent_proto_enumTypes[1].Descriptor()
}

func (OperationStatus) Type() protoreflect.EnumType {
	return &file_snapshot_agent_proto_enumTypes[1]
}

func (x OperationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationStatus.Descriptor instead.
func (OperationStatus) EnumDescriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{1}
}

type JobState int32

const (
	JobState_JOB_STATE_UNSPECIFIED   JobState = 0
	JobState_JOB_STATE_IDLE          JobState = 1
	JobState_JOB_STATE_RUNNING       JobState = 2
	JobState_JOB_STATE_TRANSITIONING JobState = 3
	JobState_JOB_STATE_SAVED         JobState = 4
	JobState_JOB_STATE_FAULTED       JobState = 5
)

// Enum value maps for JobState.
var (
	JobState_name = map[int32]string{
		0: "JOB_STATE_UNSPECIFIED",
		1: "JOB_STATE_IDLE",
		2: "JOB_STATE_RUNNING",
		3: "JOB_STATE_TRANSITIONING",
		4: "JOB_STATE_SAVED",
		5: "JOB_STATE_FAULTED",
	}
	JobState_value = map[string]int32{
		"JOB_STATE_UNSPECIFIED":   0,
		"JOB_STATE_IDLE":          1,
		"JOB_STATE_RUNNING":       2,
		"JOB_STATE_TRANSITIONING": 3,
		"JOB_STATE_SAVED":         4,
		"JOB_STATE_FAULTED":       5,
	}
)

func (x JobState) Enum() *JobState {
	p := new(JobState)
	*p = x
	return p
}

func (x JobState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobState) Descriptor() protoreflect.EnumDescriptor {
	return file_snapshot_agent_proto_enumTypes[2].Descriptor()
}

func (JobState) Type() protoreflect.EnumType {
	return &file_snapshot_agent_proto_enumTypes[2]
}

func (x JobState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobState.Descriptor instead.
func (JobState) EnumDescriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{2}
}

type SnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Group         string                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	Backend       Backend                `protobuf:"varint,3,opt,name=backend,proto3,enum=snapshot_agent.v1alpha1.Backend" json:"backend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotRequest) Reset() {
	*x = SnapshotRequest{}
	mi := &file_snapshot_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRequest) ProtoMessage() {}

func (x *SnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRequest.ProtoReflect.Descriptor instead.
func (*SnapshotRequest) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{0}
}

func (x *SnapshotRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *SnapshotRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *SnapshotRequest) GetBackend() Backend {
	if x != nil {
		return x.Backend
	}
	return Backend_BACKEND_UNSPECIFIED
}

type SnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotResponse) Reset() {
	*x = SnapshotResponse{}
	mi := &file_snapshot_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotResponse) ProtoMessage() {}

func (x *SnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotResponse.ProtoReflect.Descriptor instead.
func (*SnapshotResponse) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{1}
}

func (x *SnapshotResponse) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type RestoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Group         string                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	Backend       Backend                `protobuf:"varint,3,opt,name=backend,proto3,enum=snapshot_agent.v1alpha1.Backend" json:"backend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreRequest) Reset() {
	*x = RestoreRequest{}
	mi := &file_snapshot_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreRequest) ProtoMessage() {}

func (x *RestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreRequest.ProtoReflect.Descriptor instead.
func (*RestoreRequest) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{2}
}

func (x *RestoreRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *RestoreRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *RestoreRequest) GetBackend() Backend {
	if x != nil {
		return x.Backend
	}
	return Backend_BACKEND_UNSPECIFIED
}

type RestoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreResponse) Reset() {
	*x = RestoreResponse{}
	mi := &file_snapshot_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreResponse) ProtoMessage() {}

func (x *RestoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreResponse.ProtoReflect.Descriptor instead.
func (*RestoreResponse) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{3}
}

func (x *RestoreResponse) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type GetOperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOperationRequest) Reset() {
	*x = GetOperationRequest{}
	mi := &file_snapshot_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperationRequest) ProtoMessage() {}

func (x *GetOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperationRequest.ProtoReflect.Descriptor instead.
func (*GetOperationRequest) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{4}
}

func (x *GetOperationRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type GetOperationResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Status OperationStatus        `protobuf:"varint,1,opt,name=status,proto3,enum=snapshot_agent.v1alpha1.OperationStatus" json:"status,omitempty"`
	// storage_bytes is set on COMPLETE
	StorageBytes *int64 `protobuf:"varint,2,opt,name=storage_bytes,json=storageBytes,proto3,oneof" json:"storage_bytes,omitempty"`
	// snapshot_device_bytes is set on COMPLETE
	SnapshotDeviceBytes *int64 `protobuf:"varint,3,opt,name=snapshot_device_bytes,json=snapshotDeviceBytes,proto3,oneof" json:"snapshot_device_bytes,omitempty"`
	ElapsedMs           int64  `protobuf:"varint,4,opt,name=elapsed_ms,json=elapsedMs,proto3" json:"elapsed_ms,omitempty"`
	// error is set on FAILED
	Error         *string `protobuf:"bytes,5,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOperationResponse) Reset() {
	*x = GetOperationResponse{}
	mi := &file_snapshot_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperationResponse) ProtoMessage() {}

func (x *GetOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperationResponse.ProtoReflect.Descriptor instead.
func (*GetOperationResponse) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{5}
}

func (x *GetOperationResponse) GetStatus() OperationStatus {
	if x != nil {
		return x.Status
	}
	return OperationStatus_OPERATION_STATUS_UNSPECIFIED
}

func (x *GetOperationResponse) GetStorageBytes() int64 {
	if x != nil && x.StorageBytes != nil {
		return *x.StorageBytes
	}
	return 0
}

func (x *GetOperationResponse) GetSnapshotDeviceBytes() int64 {
	if x != nil && x.SnapshotDeviceBytes != nil {
		return *x.SnapshotDeviceBytes
	}
	return 0
}

func (x *GetOperationResponse) GetElapsedMs() int64 {
	if x != nil {
		return x.ElapsedMs
	}
	return 0
}

func (x *GetOperationResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_snapshot_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{6}
}

type JobStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	State         JobState               `protobuf:"varint,2,opt,name=state,proto3,enum=snapshot_agent.v1alpha1.JobState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobStatus) Reset() {
	*x = JobStatus{}
	mi := &file_snapshot_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStatus) ProtoMessage() {}

func (x *JobStatus) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStatus.ProtoReflect.Descriptor instead.
func (*JobStatus) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{7}
}

func (x *JobStatus) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobStatus) GetState() JobState {
	if x != nil {
		return x.State
	}
	return JobState_JOB_STATE_UNSPECIFIED
}

type AcceleratorStatus struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MemoryUsedBytes  int64                  `protobuf:"varint,2,opt,name=memory_used_bytes,json=memoryUsedBytes,proto3" json:"memory_used_bytes,omitempty"`
	MemoryTotalBytes int64                  `protobuf:"varint,3,opt,name=memory_total_bytes,json=memoryTotalBytes,proto3" json:"memory_total_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AcceleratorStatus) Reset() {
	*x = AcceleratorStatus{}
	mi := &file_snapshot_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceleratorStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceleratorStatus) ProtoMessage() {}

func (x *AcceleratorStatus) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceleratorStatus.ProtoReflect.Descriptor instead.
func (*AcceleratorStatus) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{8}
}

func (x *AcceleratorStatus) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AcceleratorStatus) GetMemoryUsedBytes() int64 {
	if x != nil {
		return x.MemoryUsedBytes
	}
	return 0
}

func (x *AcceleratorStatus) GetMemoryTotalBytes() int64 {
	if x != nil {
		return x.MemoryTotalBytes
	}
	return 0
}

type StatusResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	JobStatuses         []*JobStatus           `protobuf:"bytes,1,rep,name=job_statuses,json=jobStatuses,proto3" json:"job_statuses,omitempty"`
	AcceleratorStatuses []*AcceleratorStatus   `protobuf:"bytes,2,rep,name=accelerator_statuses,json=acceleratorStatuses,proto3" json:"accelerator_statuses,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_snapshot_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{9}
}

func (x *StatusResponse) GetJobStatuses() []*JobStatus {
	if x != nil {
		return x.JobStatuses
	}
	return nil
}

func (x *StatusResponse) GetAcceleratorStatuses() []*AcceleratorStatus {
	if x != nil {
		return x.AcceleratorStatuses
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_snapshot_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{10}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_snapshot_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{11}
}

func (x *HealthResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

var File_snapshot_agent_proto protoreflect.FileDescriptor

const file_snapshot_agent_proto_rawDesc = "" +
	"\n" +
	"\x14snapshot_agent.proto\x12\x17snapshot_agent.v1alpha1\"z\n" +
	"\x0fSnapshotRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12:\n" +
	"\abackend\x18\x03 \x01(\x0e2 .snapshot_agent.v1alpha1.BackendR\abackend\"5\n" +
	"\x10SnapshotResponse\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\"y\n" +
	"\x0eRestoreRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12:\n" +
	"\abackend\x18\x03 \x01(\x0e2 .snapshot_agent.v1alpha1.BackendR\abackend\"4\n" +
	"\x0fRestoreResponse\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\"8\n" +
	"\x13GetOperationRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\"\xab\x02\n" +
	"\x14GetOperationResponse\x12@\n" +
	"\x06status\x18\x01 \x01(\x0e2(.snapshot_agent.v1alpha1.OperationStatusR\x06status\x12(\n" +
	"\rstorage_bytes\x18\x02 \x01(\x03H\x00R\fstorageBytes\x88\x01\x01\x127\n" +
	"\x15snapshot_device_bytes\x18\x03 \x01(\x03H\x01R\x13snapshotDeviceBytes\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"elapsed_ms\x18\x04 \x01(\x03R\telapsedMs\x12\x19\n" +
	"\x05error\x18\x05 \x01(\tH\x02R\x05error\x88\x01\x01B\x10\n" +
	"\x0e_storage_bytesB\x18\n" +
	"\x16_snapshot_device_bytesB\b\n" +
	"\x06_error\"\x0f\n" +
	"\rStatusRequest\"[\n" +
	"\tJobStatus\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x127\n" +
	"\x05state\x18\x02 \x01(\x0e2!.snapshot_agent.v1alpha1.JobStateR\x05state\"}\n" +
	"\x11AcceleratorStatus\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12*\n" +
	"\x11memory_used_bytes\x18\x02 \x01(\x03R\x0fmemoryUsedBytes\x12,\n" +
	"\x12memory_total_bytes\x18\x03 \x01(\x03R\x10memoryTotalBytes\"\xb6\x01\n" +
	"\x0eStatusResponse\x12E\n" +
	"\fjob_statuses\x18\x01 \x03(\v2\".snapshot_agent.v1alpha1.JobStatusR\vjobStatuses\x12]\n" +
	"\x14accelerator_statuses\x18\x02 \x03(\v2*.snapshot_agent.v1alpha1.AcceleratorStatusR\x13acceleratorStatuses\"\x0f\n" +
	"\rHealthRequest\"*\n" +
	"\x0eHealthResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy*4\n" +
	"\aBackend\x12\x17\n" +
	"\x13BACKEND_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fBACKEND_CUDA\x10\x01*\x8d\x01\n" +
	"\x0fOperationStatus\x12 \n" +
	"\x1cOPERATION_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18OPERATION_STATUS_PENDING\x10\x01\x12\x1d\n" +
	"\x19OPERATION_STATUS_COMPLETE\x10\x02\x12\x1b\n" +
	"\x17OPERATION_STATUS_FAILED\x10\x03*\x99\x01\n" +
	"\bJobState\x12\x19\n" +
	"\x15JOB_STATE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eJOB_STATE_IDLE\x10\x01\x12\x15\n" +
	"\x11JOB_STATE_RUNNING\x10\x02\x12\x1b\n" +
	"\x17JOB_STATE_TRANSITIONING\x10\x03\x12\x13\n" +
	"\x0fJOB_STATE_SAVED\x10\x04\x12\x15\n" +
	"\x11JOB_STATE_FAULTED\x10\x052\xf8\x03\n" +
	"\x14SnapshotAgentService\x12_\n" +
	"\bSnapshot\x12(.snapshot_agent.v1alpha1.SnapshotRequest\x1a).snapshot_agent.v1alpha1.SnapshotResponse\x12\\\n" +
	"\aRestore\x12'.snapshot_agent.v1alpha1.RestoreRequest\x1a(.snapshot_agent.v1alpha1.RestoreResponse\x12k\n" +
	"\fGetOperation\x12,.snapshot_agent.v1alpha1.GetOperationRequest\x1a-.snapshot_agent.v1alpha1.GetOperationResponse\x12Y\n" +
	"\x06Status\x12&.snapshot_agent.v1alpha1.StatusRequest\x1a'.snapshot_agent.v1alpha1.StatusResponse\x12Y\n" +
	"\x06Health\x12&.snapshot_agent.v1alpha1.HealthRequest\x1a'.snapshot_agent.v1alpha1.HealthResponseB\\ZZgithub.com/llm-d-incubation/llm-d-rl-time-slicing/pkg/snapshot-agent/api/v1alpha1;v1alpha1b\x06proto3"

var (
	file_snapshot_agent_proto_rawDescOnce sync.Once
	file_snapshot_agent_proto_rawDescData []byte
)

func file_snapshot_agent_proto_rawDescGZIP() []byte {
	file_snapshot_agent_proto_rawDescOnce.Do(func() {
		file_snapshot_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_snapshot_agent_proto_rawDesc), len(file_snapshot_agent_proto_rawDesc)))
	})
	return file_snapshot_agent_proto_rawDescData
}

var file_snapshot_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_snapshot_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_snapshot_agent_proto_goTypes = []any{
	(Backend)(0),                 // 0: snapshot_agent.v1alpha1.Backend
	(OperationStatus)(0),         // 1: snapshot_agent.v1alpha1.OperationStatus
	(JobState)(0),                // 2: snapshot_agent.v1alpha1.JobState
	(*SnapshotRequest)(nil),      // 3: snapshot_agent.v1alpha1.SnapshotRequest
	(*SnapshotResponse)(nil),     // 4: snapshot_agent.v1alpha1.SnapshotResponse
	(*RestoreRequest)(nil),       // 5: snapshot_agent.v1alpha1.RestoreRequest
	(*RestoreResponse)(nil),      // 6: snapshot_agent.v1alpha1.RestoreResponse
	(*GetOperationRequest)(nil),  // 7: snapshot_agent.v1alpha1.GetOperationRequest
	(*GetOperationResponse)(nil), // 8: snapshot_agent.v1alpha1.GetOperationResponse
	(*StatusRequest)(nil),        // 9: snapshot_agent.v1alpha1.StatusRequest
	(*JobStatus)(nil),            // 10: snapshot_agent.v1alpha1.JobStatus
	(*AcceleratorStatus)(nil),    // 11: snapshot_agent.v1alpha1.AcceleratorStatus
	(*StatusResponse)(nil),       // 12: snapshot_agent.v1alpha1.StatusResponse
	(*HealthRequest)(nil),        // 13: snapshot_agent.v1alpha1.HealthRequest
	(*HealthResponse)(nil),       // 14: snapshot_agent.v1alpha1.HealthResponse
}
var file_snapshot_agent_proto_depIdxs = []int32{
	0,  // 0: snapshot_agent.v1alpha1.SnapshotRequest.backend:type_name -> snapshot_agent.v1alpha1.Backend
	0,  // 1: snapshot_agent.v1alpha1.RestoreRequest.backend:type_name -> snapshot_agent.v1alpha1.Backend
	1,  // 2: snapshot_agent.v1alpha1.GetOperationResponse.status:type_name -> snapshot_agent.v1alpha1.OperationStatus
	2,  // 3: snapshot_agent.v1alpha1.JobStatus.state:type_name -> snapshot_agent.v1alpha1.JobState
	10, // 4: snapshot_agent.v1alpha1.StatusResponse.job_statuses:type_name -> snapshot_agent.v1alpha1.JobStatus
	11, // 5: snapshot_agent.v1alpha1.StatusResponse.accelerator_statuses:type_name -> snapshot_agent.v1alpha1.AcceleratorStatus
	3,  // 6: snapshot_agent.v1alpha1.SnapshotAgentService.Snapshot:input_type -> snapshot_agent.v1alpha1.SnapshotRequest
	5,  // 7: snapshot_agent.v1alpha1.SnapshotAgentService.Restore:input_type -> snapshot_agent.v1alpha1.RestoreRequest
	7,  // 8: snapshot_agent.v1alpha1.SnapshotAgentService.GetOperation:input_type -> snapshot_agent.v1alpha1.GetOperationRequest
	9,  // 9: snapshot_agent.v1alpha1.SnapshotAgentService.Status:input_type -> snapshot_agent.v1alpha1.StatusRequest
	13, // 10: snapshot_agent.v1alpha1.SnapshotAgentService.Health:input_type -> snapshot_agent.v1alpha1.HealthRequest
	4,  // 11: snapshot_agent.v1alpha1.SnapshotAgentService.Snapshot:output_type -> snapshot_agent.v1alpha1.SnapshotResponse
	6,  // 12: snapshot_agent.v1alpha1.SnapshotAgentService.Restore:output_type -> snapshot_agent.v1alpha1.RestoreResponse
	8,  // 13: snapshot_agent.v1alpha1.SnapshotAgentService.GetOperation:output_type -> snapshot_agent.v1alpha1.GetOperationResponse
	12, // 14: snapshot_agent.v1alpha1.SnapshotAgentService.Status:output_type -> snapshot_agent.v1alpha1.StatusResponse
	14, // 15: snapshot_agent.v1alpha1.SnapshotAgentService.Health:output_type -> snapshot_agent.v1alpha1.HealthResponse
	11, // [11:16] is the sub-list for method output_type
	6,  // [6:11] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_snapshot_agent_proto_init() }
func file_snapshot_agent_proto_init() {
	if File_snapshot_agent_proto != nil {
		return
	}
	file_snapshot_agent_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_snapshot_agent_proto_rawDesc), len(file_snapshot_agent_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_snapshot_agent_proto_goTypes,
		DependencyIndexes: file_snapshot_agent_proto_depIdxs,
		EnumInfos:         file_snapshot_agent_proto_enumTypes,
		MessageInfos:      file_snapshot_agent_proto_msgTypes,
	}.Build()
	File_snapshot_agent_proto = out.File
	file_snapshot_agent_proto_goTypes = nil
	file_snapshot_agent_proto_depIdxs = nil
}
