// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: snapshot_agent.proto

package v1alpha1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SnapshotAgentService_Snapshot_FullMethodName     = "/snapshot_agent.v1alpha1.SnapshotAgentService/Snapshot"
	SnapshotAgentService_Restore_FullMethodName      = "/snapshot_agent.v1alpha1.SnapshotAgentService/Restore"
	SnapshotAgentService_GetOperation_FullMethodName = "/snapshot_agent.v1alpha1.SnapshotAgentService/GetOperation"
	SnapshotAgentService_Status_FullMethodName       = "/snapshot_agent.v1alpha1.SnapshotAgentService/Status"
	SnapshotAgentService_Health_FullMethodName       = "/snapshot_agent.v1alpha1.SnapshotAgentService/Health"
)

// SnapshotAgentServiceClient is the client API for SnapshotAgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SnapshotAgentService provides APIs for managing accelerator snapshots.
type SnapshotAgentServiceClient interface {
	// Snapshot triggers an asynchronous snapshot of the accelerator context for a job.
	Snapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*SnapshotResponse, error)
	// Restore triggers an asynchronous restoration of the accelerator context for a job.
	Restore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*RestoreResponse, error)
	// GetOperation polls the status of a long-running snapshot or restore operation.
	GetOperation(ctx context.Context, in *GetOperationRequest, opts ...grpc.CallOption) (*GetOperationResponse, error)
	// Status returns the current state of jobs and accelerators on the node.
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	// Health returns the health status of the agent.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type snapshotAgentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSnapshotAgentServiceClient(cc grpc.ClientConnInterface) SnapshotAgentServiceClient {
	return &snapshotAgentServiceClient{cc}
}

func (c *snapshotAgentServiceClient) Snapshot(ctx context.Context, in *SnapshotRequest, opts ...grpc.CallOption) (*SnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SnapshotResponse)
	err := c.cc.Invoke(ctx, SnapshotAgentService_Snapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snapshotAgentServiceClient) Restore(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*RestoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestoreResponse)
	err := c.cc.Invoke(ctx, SnapshotAgentService_Restore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snapshotAgentServiceClient) GetOperation(ctx context.Context, in *GetOperationRequest, opts ...grpc.CallOption) (*GetOperationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOperationResponse)
	err := c.cc.Invoke(ctx, SnapshotAgentService_GetOperation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snapshotAgentServiceClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, SnapshotAgentService_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snapshotAgentServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, SnapshotAgentService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SnapshotAgentServiceServer is the server API for SnapshotAgentService service.
// All implementations must embed UnimplementedSnapshotAgentServiceServer
// for forward compatibility.
//
// SnapshotAgentService provides APIs for managing accelerator snapshots.
type SnapshotAgentServiceServer interface {
	// Snapshot triggers an asynchronous snapshot of the accelerator context for a job.
	Snapshot(context.Context, *SnapshotRequest) (*SnapshotResponse, error)
	// Restore triggers an asynchronous restoration of the accelerator context for a job.
	Restore(context.Context, *RestoreRequest) (*RestoreResponse, error)
	// GetOperation polls the status of a long-running snapshot or restore operation.
	GetOperation(context.Context, *GetOperationRequest) (*GetOperationResponse, error)
	// Status returns the current state of jobs and accelerators on the node.
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	// Health returns the health status of the agent.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedSnapshotAgentServiceServer()
}

// UnimplementedSnapshotAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSnapshotAgentServiceServer struct{}

func (UnimplementedSnapshotAgentServiceServer) Snapshot(context.Context, *SnapshotRequest) (*SnapshotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Snapshot not implemented")
}
func (UnimplementedSnapshotAgentServiceServer) Restore(context.Context, *RestoreRequest) (*RestoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Restore not implemented")
}
func (UnimplementedSnapshotAgentServiceServer) GetOperation(context.Context, *GetOperationRequest) (*GetOperationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetOperation not implemented")
}
func (UnimplementedSnapshotAgentServiceServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedSnapshotAgentServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedSnapshotAgentServiceServer) mustEmbedUnimplementedSnapshotAgentServiceServer() {}
func (UnimplementedSnapshotAgentServiceServer) testEmbeddedByValue()                              {}

// UnsafeSnapshotAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SnapshotAgentServiceServer will
// result in compilation errors.
type UnsafeSnapshotAgentServiceServer interface {
	mustEmbedUnimplementedSnapshotAgentServiceServer()
}

func RegisterSnapshotAgentServiceServer(s grpc.ServiceRegistrar, srv SnapshotAgentServiceServer) {
	// If the following call pancis, it indicates UnimplementedSnapshotAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SnapshotAgentService_ServiceDesc, srv)
}

func _SnapshotAgentService_Snapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapshotAgentServiceServer).Snapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnapshotAgentService_Snapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapshotAgentServiceServer).Snapshot(ctx, req.(*SnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnapshotAgentService_Restore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapshotAgentServiceServer).Restore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnapshotAgentService_Restore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapshotAgentServiceServer).Restore(ctx, req.(*RestoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnapshotAgentService_GetOperation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapshotAgentServiceServer).GetOperation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnapshotAgentService_GetOperation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapshotAgentServiceServer).GetOperation(ctx, req.(*GetOperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnapshotAgentService_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapshotAgentServiceServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnapshotAgentService_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapshotAgentServiceServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnapshotAgentService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapshotAgentServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnapshotAgentService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapshotAgentServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SnapshotAgentService_ServiceDesc is the grpc.ServiceDesc for SnapshotAgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SnapshotAgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "snapshot_agent.v1alpha1.SnapshotAgentService",
	HandlerType: (*SnapshotAgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Snapshot",
			Handler:    _SnapshotAgentService_Snapshot_Handler,
		},
		{
			MethodName: "Restore",
			Handler:    _SnapshotAgentService_Restore_Handler,
		},
		{
			MethodName: "GetOperation",
			Handler:    _SnapshotAgentService_GetOperation_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _SnapshotAgentService_Status_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _SnapshotAgentService_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "snapshot_agent.proto",
}
