// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: snapshot_agent.proto

package v1alpha1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Deprecated: Marked as deprecated in snapshot_agent.proto.
type Backend int32

const (
	Backend_BACKEND_UNSPECIFIED Backend = 0
	Backend_BACKEND_CUDA        Backend = 1
)

// Enum value maps for Backend.
var (
	Backend_name = map[int32]string{
		0: "BACKEND_UNSPECIFIED",
		1: "BACKEND_CUDA",
	}
	Backend_value = map[string]int32{
		"BACKEND_UNSPECIFIED": 0,
		"BACKEND_CUDA":        1,
	}
)

func (x Backend) Enum() *Backend {
	p := new(Backend)
	*p = x
	return p
}

func (x Backend) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Backend) Descriptor() protoreflect.EnumDescriptor {
	return file_snapshot_agent_proto_enumTypes[0].Descriptor()
}

func (Backend) Type() protoreflect.EnumType {
	return &file_snapshot_agent_proto_enumTypes[0]
}

func (x Backend) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Backend.Descriptor instead.
func (Backend) EnumDescriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{0}
}

// App identifies the HTTP API dialect of an application-aware workload.
// It grows only when a new HTTP dialect ships; workloads reached through a
// registered workload channel never need an entry here.
type App int32

const (
	App_APP_UNSPECIFIED App = 0
	// vLLM's dev-mode sleep API: POST /sleep?level=N, POST /wake_up?tags=...
	// Requires VLLM_SERVER_DEV_MODE=1 and --enable-sleep-mode on the server.
	App_APP_VLLM App = 1
	// SGLang's memory API: POST /release_memory_occupation and
	// POST /resume_memory_occupation (JSON body). Requires
	// --enable-memory-saver; whether suspended weights are preserved is fixed
	// at server launch by --enable-weights-cpu-backup (see SuspendMode).
	App_APP_SGLANG App = 2
)

// Enum value maps for App.
var (
	App_name = map[int32]string{
		0: "APP_UNSPECIFIED",
		1: "APP_VLLM",
		2: "APP_SGLANG",
	}
	App_value = map[string]int32{
		"APP_UNSPECIFIED": 0,
		"APP_VLLM":        1,
		"APP_SGLANG":      2,
	}
)

func (x App) Enum() *App {
	p := new(App)
	*p = x
	return p
}

func (x App) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (App) Descriptor() protoreflect.EnumDescriptor {
	return file_snapshot_agent_proto_enumTypes[1].Descriptor()
}

func (App) Type() protoreflect.EnumType {
	return &file_snapshot_agent_proto_enumTypes[1]
}

func (x App) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use App.Descriptor instead.
func (App) EnumDescriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{1}
}

// SuspendMode states what happens to the workload's durable state (model
// weights, optimizer state) while suspended. Region-level engine specifics
// (e.g. KV cache is discarded by engines in either mode) are handled by the
// application dialect.
type SuspendMode int32

const (
	// Use the application's default behavior.
	SuspendMode_SUSPEND_MODE_UNSPECIFIED SuspendMode = 0
	// State is preserved in host memory; Restore copies it back.
	SuspendMode_SUSPEND_MODE_OFFLOAD SuspendMode = 1
	// State is dropped; the application must re-provision it after Restore
	// (e.g. RL weight sync). Unsupported by workloads that cannot reconstruct
	// state, such as trainers.
	SuspendMode_SUSPEND_MODE_DISCARD SuspendMode = 2
)

// Enum value maps for SuspendMode.
var (
	SuspendMode_name = map[int32]string{
		0: "SUSPEND_MODE_UNSPECIFIED",
		1: "SUSPEND_MODE_OFFLOAD",
		2: "SUSPEND_MODE_DISCARD",
	}
	SuspendMode_value = map[string]int32{
		"SUSPEND_MODE_UNSPECIFIED": 0,
		"SUSPEND_MODE_OFFLOAD":     1,
		"SUSPEND_MODE_DISCARD":     2,
	}
)

func (x SuspendMode) Enum() *SuspendMode {
	p := new(SuspendMode)
	*p = x
	return p
}

func (x SuspendMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SuspendMode) Descriptor() protoreflect.EnumDescriptor {
	return file_snapshot_agent_proto_enumTypes[2].Descriptor()
}

func (SuspendMode) Type() protoreflect.EnumType {
	return &file_snapshot_agent_proto_enumTypes[2]
}

func (x SuspendMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SuspendMode.Descriptor instead.
func (SuspendMode) EnumDescriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{2}
}

type OperationStatus int32

const (
	OperationStatus_OPERATION_STATUS_UNSPECIFIED OperationStatus = 0
	OperationStatus_OPERATION_STATUS_PENDING     OperationStatus = 1
	OperationStatus_OPERATION_STATUS_COMPLETE    OperationStatus = 2
	OperationStatus_OPERATION_STATUS_FAILED      OperationStatus = 3
)

// Enum value maps for OperationStatus.
var (
	OperationStatus_name = map[int32]string{
		0: "OPERATION_STATUS_UNSPECIFIED",
		1: "OPERATION_STATUS_PENDING",
		2: "OPERATION_STATUS_COMPLETE",
		3: "OPERATION_STATUS_FAILED",
	}
	OperationStatus_value = map[string]int32{
		"OPERATION_STATUS_UNSPECIFIED": 0,
		"OPERATION_STATUS_PENDING":     1,
		"OPERATION_STATUS_COMPLETE":    2,
		"OPERATION_STATUS_FAILED":      3,
	}
)

func (x OperationStatus) Enum() *OperationStatus {
	p := new(OperationStatus)
	*p = x
	return p
}

func (x OperationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_snapshot_agent_proto_enumTypes[3].Descriptor()
}

func (OperationStatus) Type() protoreflect.EnumType {
	return &file_snapshot_agent_proto_enumTypes[3]
}

func (x OperationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationStatus.Descriptor instead.
func (OperationStatus) EnumDescriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{3}
}

type JobState int32

const (
	JobState_JOB_STATE_UNSPECIFIED   JobState = 0
	JobState_JOB_STATE_IDLE          JobState = 1
	JobState_JOB_STATE_RUNNING       JobState = 2
	JobState_JOB_STATE_TRANSITIONING JobState = 3
	JobState_JOB_STATE_SAVED         JobState = 4
	JobState_JOB_STATE_FAULTED       JobState = 5
)

// Enum value maps for JobState.
var (
	JobState_name = map[int32]string{
		0: "JOB_STATE_UNSPECIFIED",
		1: "JOB_STATE_IDLE",
		2: "JOB_STATE_RUNNING",
		3: "JOB_STATE_TRANSITIONING",
		4: "JOB_STATE_SAVED",
		5: "JOB_STATE_FAULTED",
	}
	JobState_value = map[string]int32{
		"JOB_STATE_UNSPECIFIED":   0,
		"JOB_STATE_IDLE":          1,
		"JOB_STATE_RUNNING":       2,
		"JOB_STATE_TRANSITIONING": 3,
		"JOB_STATE_SAVED":         4,
		"JOB_STATE_FAULTED":       5,
	}
)

func (x JobState) Enum() *JobState {
	p := new(JobState)
	*p = x
	return p
}

func (x JobState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobState) Descriptor() protoreflect.EnumDescriptor {
	return file_snapshot_agent_proto_enumTypes[4].Descriptor()
}

func (JobState) Type() protoreflect.EnumType {
	return &file_snapshot_agent_proto_enumTypes[4]
}

func (x JobState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobState.Descriptor instead.
func (JobState) EnumDescriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{4}
}

// ProcessTarget specifies a set of process IDs (PIDs) to target.
// This is optional in some deployment modes (like 'k8s' where PIDs can be discovered automatically),
// but required in others (like 'standalone').
// In the future, we may add other target types (e.g., MemoryTarget)
// to support different backends.
type ProcessTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pids          []int32                `protobuf:"varint,1,rep,packed,name=pids,proto3" json:"pids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessTarget) Reset() {
	*x = ProcessTarget{}
	mi := &file_snapshot_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessTarget) ProtoMessage() {}

func (x *ProcessTarget) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessTarget.ProtoReflect.Descriptor instead.
func (*ProcessTarget) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{0}
}

func (x *ProcessTarget) GetPids() []int32 {
	if x != nil {
		return x.Pids
	}
	return nil
}

type CudaBackendConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ExplicitTarget *ProcessTarget         `protobuf:"bytes,1,opt,name=explicit_target,json=explicitTarget,proto3" json:"explicit_target,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CudaBackendConfig) Reset() {
	*x = CudaBackendConfig{}
	mi := &file_snapshot_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CudaBackendConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CudaBackendConfig) ProtoMessage() {}

func (x *CudaBackendConfig) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CudaBackendConfig.ProtoReflect.Descriptor instead.
func (*CudaBackendConfig) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{1}
}

func (x *CudaBackendConfig) GetExplicitTarget() *ProcessTarget {
	if x != nil {
		return x.ExplicitTarget
	}
	return nil
}

// Configuration for the Direct Memory (process-level) backend.
type DirectMemoryBackendConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The target processes to checkpoint/restore.
	ExplicitTarget *ProcessTarget `protobuf:"bytes,1,opt,name=explicit_target,json=explicitTarget,proto3" json:"explicit_target,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DirectMemoryBackendConfig) Reset() {
	*x = DirectMemoryBackendConfig{}
	mi := &file_snapshot_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DirectMemoryBackendConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DirectMemoryBackendConfig) ProtoMessage() {}

func (x *DirectMemoryBackendConfig) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DirectMemoryBackendConfig.ProtoReflect.Descriptor instead.
func (*DirectMemoryBackendConfig) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{2}
}

func (x *DirectMemoryBackendConfig) GetExplicitTarget() *ProcessTarget {
	if x != nil {
		return x.ExplicitTarget
	}
	return nil
}

// Configuration for the TPU (libtpu) backend. Checkpoint/restore of TPU state
// for running processes via libtpu's control-pipe protocol (the tpu-checkpoint
// CLI); targets must run with LIBTPU_CHECKPOINTING_ENABLED=true.
type TpuBackendConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The target processes to checkpoint/restore. Optional in 'k8s' deployment
	// mode (PIDs are discovered from the job's pods), required in 'standalone'.
	// Restore is a slice-wide rendezvous inside libtpu: all of a job's TPU
	// processes must be restored in one request, and a restore must never be
	// retried.
	ExplicitTarget *ProcessTarget `protobuf:"bytes,1,opt,name=explicit_target,json=explicitTarget,proto3" json:"explicit_target,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TpuBackendConfig) Reset() {
	*x = TpuBackendConfig{}
	mi := &file_snapshot_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TpuBackendConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TpuBackendConfig) ProtoMessage() {}

func (x *TpuBackendConfig) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TpuBackendConfig.ProtoReflect.Descriptor instead.
func (*TpuBackendConfig) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{3}
}

func (x *TpuBackendConfig) GetExplicitTarget() *ProcessTarget {
	if x != nil {
		return x.ExplicitTarget
	}
	return nil
}

// AppEndpointConfig suspends/resumes an application-aware workload through
// its HTTP API. Callers using this config supply the endpoints and therefore
// know which application they deployed; `app` selects the HTTP dialect.
type AppEndpointConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	App   App                    `protobuf:"varint,1,opt,name=app,proto3,enum=snapshot_agent.v1alpha1.App" json:"app,omitempty"`
	// HTTP endpoint(s) of the application server(s), e.g. "http://localhost:8000".
	Endpoints []string `protobuf:"bytes,2,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	// See SuspendMode. For APP_SGLANG this is advisory: the effective mode is
	// fixed by the server's launch flags.
	Mode SuspendMode `protobuf:"varint,3,opt,name=mode,proto3,enum=snapshot_agent.v1alpha1.SuspendMode" json:"mode,omitempty"`
	// Region tags, e.g. "weights", "kv_cache". Free-form strings validated by
	// the application; if empty, the application's full default region set is
	// used. On Snapshot, tags select what to suspend (where the application
	// supports it); on Restore, what to bring back.
	Tags          []string `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppEndpointConfig) Reset() {
	*x = AppEndpointConfig{}
	mi := &file_snapshot_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppEndpointConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppEndpointConfig) ProtoMessage() {}

func (x *AppEndpointConfig) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppEndpointConfig.ProtoReflect.Descriptor instead.
func (*AppEndpointConfig) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{4}
}

func (x *AppEndpointConfig) GetApp() App {
	if x != nil {
		return x.App
	}
	return App_APP_UNSPECIFIED
}

func (x *AppEndpointConfig) GetEndpoints() []string {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

func (x *AppEndpointConfig) GetMode() SuspendMode {
	if x != nil {
		return x.Mode
	}
	return SuspendMode_SUSPEND_MODE_UNSPECIFIED
}

func (x *AppEndpointConfig) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// AppChannelConfig suspends/resumes an application-aware workload through
// its registered workload channel (see WorkloadChannel). The workload is
// addressed by the request's job_id; callers need no endpoints and no
// knowledge of which application is running.
type AppChannelConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// See SuspendMode. If unspecified, the workload's registered default mode
	// is used (OFFLOAD if the workload did not declare one).
	Mode SuspendMode `protobuf:"varint,1,opt,name=mode,proto3,enum=snapshot_agent.v1alpha1.SuspendMode" json:"mode,omitempty"`
	// Region tags; see AppEndpointConfig.tags.
	Tags          []string `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppChannelConfig) Reset() {
	*x = AppChannelConfig{}
	mi := &file_snapshot_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppChannelConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppChannelConfig) ProtoMessage() {}

func (x *AppChannelConfig) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppChannelConfig.ProtoReflect.Descriptor instead.
func (*AppChannelConfig) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{5}
}

func (x *AppChannelConfig) GetMode() SuspendMode {
	if x != nil {
		return x.Mode
	}
	return SuspendMode_SUSPEND_MODE_UNSPECIFIED
}

func (x *AppChannelConfig) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type BackendConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Backend:
	//
	//	*BackendConfig_Cuda
	//	*BackendConfig_AppEndpoint
	//	*BackendConfig_AppChannel
	//	*BackendConfig_DirectMemory
	//	*BackendConfig_Tpu
	Backend       isBackendConfig_Backend `protobuf_oneof:"backend"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackendConfig) Reset() {
	*x = BackendConfig{}
	mi := &file_snapshot_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackendConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendConfig) ProtoMessage() {}

func (x *BackendConfig) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendConfig.ProtoReflect.Descriptor instead.
func (*BackendConfig) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{6}
}

func (x *BackendConfig) GetBackend() isBackendConfig_Backend {
	if x != nil {
		return x.Backend
	}
	return nil
}

func (x *BackendConfig) GetCuda() *CudaBackendConfig {
	if x != nil {
		if x, ok := x.Backend.(*BackendConfig_Cuda); ok {
			return x.Cuda
		}
	}
	return nil
}

func (x *BackendConfig) GetAppEndpoint() *AppEndpointConfig {
	if x != nil {
		if x, ok := x.Backend.(*BackendConfig_AppEndpoint); ok {
			return x.AppEndpoint
		}
	}
	return nil
}

func (x *BackendConfig) GetAppChannel() *AppChannelConfig {
	if x != nil {
		if x, ok := x.Backend.(*BackendConfig_AppChannel); ok {
			return x.AppChannel
		}
	}
	return nil
}

func (x *BackendConfig) GetDirectMemory() *DirectMemoryBackendConfig {
	if x != nil {
		if x, ok := x.Backend.(*BackendConfig_DirectMemory); ok {
			return x.DirectMemory
		}
	}
	return nil
}

func (x *BackendConfig) GetTpu() *TpuBackendConfig {
	if x != nil {
		if x, ok := x.Backend.(*BackendConfig_Tpu); ok {
			return x.Tpu
		}
	}
	return nil
}

type isBackendConfig_Backend interface {
	isBackendConfig_Backend()
}

type BackendConfig_Cuda struct {
	Cuda *CudaBackendConfig `protobuf:"bytes,1,opt,name=cuda,proto3,oneof"`
}

type BackendConfig_AppEndpoint struct {
	AppEndpoint *AppEndpointConfig `protobuf:"bytes,2,opt,name=app_endpoint,json=appEndpoint,proto3,oneof"`
}

type BackendConfig_AppChannel struct {
	AppChannel *AppChannelConfig `protobuf:"bytes,3,opt,name=app_channel,json=appChannel,proto3,oneof"`
}

type BackendConfig_DirectMemory struct {
	DirectMemory *DirectMemoryBackendConfig `protobuf:"bytes,4,opt,name=direct_memory,json=directMemory,proto3,oneof"`
}

type BackendConfig_Tpu struct {
	Tpu *TpuBackendConfig `protobuf:"bytes,5,opt,name=tpu,proto3,oneof"`
}

func (*BackendConfig_Cuda) isBackendConfig_Backend() {}

func (*BackendConfig_AppEndpoint) isBackendConfig_Backend() {}

func (*BackendConfig_AppChannel) isBackendConfig_Backend() {}

func (*BackendConfig_DirectMemory) isBackendConfig_Backend() {}

func (*BackendConfig_Tpu) isBackendConfig_Backend() {}

// WorkloadCapabilities is declared by a workload at registration and lets the
// agent validate and resolve snapshot parameters without knowing the
// application.
type WorkloadCapabilities struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Suspend modes the workload can execute. If empty, no validation is
	// performed. A trainer that cannot reconstruct dropped state would
	// advertise only SUSPEND_MODE_OFFLOAD.
	SupportedModes []SuspendMode `protobuf:"varint,1,rep,packed,name=supported_modes,json=supportedModes,proto3,enum=snapshot_agent.v1alpha1.SuspendMode" json:"supported_modes,omitempty"`
	// Mode used when a snapshot request leaves the mode unspecified. If unset,
	// SUSPEND_MODE_OFFLOAD is used.
	DefaultMode SuspendMode `protobuf:"varint,2,opt,name=default_mode,json=defaultMode,proto3,enum=snapshot_agent.v1alpha1.SuspendMode" json:"default_mode,omitempty"`
	// Region tags the workload understands, e.g. "weights", "kv_cache".
	Tags          []string `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadCapabilities) Reset() {
	*x = WorkloadCapabilities{}
	mi := &file_snapshot_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadCapabilities) ProtoMessage() {}

func (x *WorkloadCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadCapabilities.ProtoReflect.Descriptor instead.
func (*WorkloadCapabilities) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{7}
}

func (x *WorkloadCapabilities) GetSupportedModes() []SuspendMode {
	if x != nil {
		return x.SupportedModes
	}
	return nil
}

func (x *WorkloadCapabilities) GetDefaultMode() SuspendMode {
	if x != nil {
		return x.DefaultMode
	}
	return SuspendMode_SUSPEND_MODE_UNSPECIFIED
}

func (x *WorkloadCapabilities) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// RegisterWorkload is the first message a workload sends on a
// WorkloadChannel stream. Re-registering a job_id replaces the previous
// stream.
type RegisterWorkload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// job_id identifies the job this workload belongs to and must be unique
	// per agent (jobs are node-scoped; group does not namespace job IDs).
	// Snapshot/Restore requests carrying an AppChannelConfig are routed to the
	// stream registered under the same job_id.
	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// group is an optional identifier for a set of related jobs.
	Group         string                `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	Capabilities  *WorkloadCapabilities `protobuf:"bytes,3,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWorkload) Reset() {
	*x = RegisterWorkload{}
	mi := &file_snapshot_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWorkload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWorkload) ProtoMessage() {}

func (x *RegisterWorkload) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWorkload.ProtoReflect.Descriptor instead.
func (*RegisterWorkload) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{8}
}

func (x *RegisterWorkload) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *RegisterWorkload) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *RegisterWorkload) GetCapabilities() *WorkloadCapabilities {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// CommandResult acknowledges completion of an AgentCommand.
type CommandResult struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	CommandId string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Ok        bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	// error is set when ok is false.
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_snapshot_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{9}
}

func (x *CommandResult) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandResult) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *CommandResult) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type WorkloadMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*WorkloadMessage_Register
	//	*WorkloadMessage_Result
	Message       isWorkloadMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkloadMessage) Reset() {
	*x = WorkloadMessage{}
	mi := &file_snapshot_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkloadMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkloadMessage) ProtoMessage() {}

func (x *WorkloadMessage) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkloadMessage.ProtoReflect.Descriptor instead.
func (*WorkloadMessage) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{10}
}

func (x *WorkloadMessage) GetMessage() isWorkloadMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *WorkloadMessage) GetRegister() *RegisterWorkload {
	if x != nil {
		if x, ok := x.Message.(*WorkloadMessage_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *WorkloadMessage) GetResult() *CommandResult {
	if x != nil {
		if x, ok := x.Message.(*WorkloadMessage_Result); ok {
			return x.Result
		}
	}
	return nil
}

type isWorkloadMessage_Message interface {
	isWorkloadMessage_Message()
}

type WorkloadMessage_Register struct {
	Register *RegisterWorkload `protobuf:"bytes,1,opt,name=register,proto3,oneof"`
}

type WorkloadMessage_Result struct {
	Result *CommandResult `protobuf:"bytes,2,opt,name=result,proto3,oneof"`
}

func (*WorkloadMessage_Register) isWorkloadMessage_Message() {}

func (*WorkloadMessage_Result) isWorkloadMessage_Message() {}

// SnapshotCommand instructs the workload to suspend. The mode is fully
// resolved by the agent (never SUSPEND_MODE_UNSPECIFIED on the wire).
type SnapshotCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          SuspendMode            `protobuf:"varint,1,opt,name=mode,proto3,enum=snapshot_agent.v1alpha1.SuspendMode" json:"mode,omitempty"`
	Tags          []string               `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotCommand) Reset() {
	*x = SnapshotCommand{}
	mi := &file_snapshot_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotCommand) ProtoMessage() {}

func (x *SnapshotCommand) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotCommand.ProtoReflect.Descriptor instead.
func (*SnapshotCommand) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{11}
}

func (x *SnapshotCommand) GetMode() SuspendMode {
	if x != nil {
		return x.Mode
	}
	return SuspendMode_SUSPEND_MODE_UNSPECIFIED
}

func (x *SnapshotCommand) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// RestoreCommand instructs the workload to resume.
type RestoreCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []string               `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreCommand) Reset() {
	*x = RestoreCommand{}
	mi := &file_snapshot_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreCommand) ProtoMessage() {}

func (x *RestoreCommand) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreCommand.ProtoReflect.Descriptor instead.
func (*RestoreCommand) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{12}
}

func (x *RestoreCommand) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// AgentCommand is pushed by the agent to a registered workload. Each command
// carries a unique command_id and is sent at most once; the workload replies
// with a CommandResult bearing the same command_id.
type AgentCommand struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	CommandId string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	// Types that are valid to be assigned to Command:
	//
	//	*AgentCommand_Snapshot
	//	*AgentCommand_Restore
	Command       isAgentCommand_Command `protobuf_oneof:"command"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentCommand) Reset() {
	*x = AgentCommand{}
	mi := &file_snapshot_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCommand) ProtoMessage() {}

func (x *AgentCommand) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCommand.ProtoReflect.Descriptor instead.
func (*AgentCommand) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{13}
}

func (x *AgentCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *AgentCommand) GetCommand() isAgentCommand_Command {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *AgentCommand) GetSnapshot() *SnapshotCommand {
	if x != nil {
		if x, ok := x.Command.(*AgentCommand_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

func (x *AgentCommand) GetRestore() *RestoreCommand {
	if x != nil {
		if x, ok := x.Command.(*AgentCommand_Restore); ok {
			return x.Restore
		}
	}
	return nil
}

type isAgentCommand_Command interface {
	isAgentCommand_Command()
}

type AgentCommand_Snapshot struct {
	Snapshot *SnapshotCommand `protobuf:"bytes,2,opt,name=snapshot,proto3,oneof"`
}

type AgentCommand_Restore struct {
	Restore *RestoreCommand `protobuf:"bytes,3,opt,name=restore,proto3,oneof"`
}

func (*AgentCommand_Snapshot) isAgentCommand_Command() {}

func (*AgentCommand_Restore) isAgentCommand_Command() {}

type SnapshotRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// job_id is the unique identifier for the job, unique per agent
	// (group does not namespace job IDs).
	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// group is an optional identifier for a set of related jobs.
	Group string `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	// Deprecated: Use backend_config instead.
	//
	// Deprecated: Marked as deprecated in snapshot_agent.proto.
	Backend Backend `protobuf:"varint,3,opt,name=backend,proto3,enum=snapshot_agent.v1alpha1.Backend" json:"backend,omitempty"`
	// backend_config specifies the backend-specific configuration for the snapshot.
	// If omitted, the default backend (CUDA) will be used with default discovery
	// based on the deployment mode.
	BackendConfig *BackendConfig `protobuf:"bytes,4,opt,name=backend_config,json=backendConfig,proto3" json:"backend_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotRequest) Reset() {
	*x = SnapshotRequest{}
	mi := &file_snapshot_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRequest) ProtoMessage() {}

func (x *SnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRequest.ProtoReflect.Descriptor instead.
func (*SnapshotRequest) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{14}
}

func (x *SnapshotRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *SnapshotRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

// Deprecated: Marked as deprecated in snapshot_agent.proto.
func (x *SnapshotRequest) GetBackend() Backend {
	if x != nil {
		return x.Backend
	}
	return Backend_BACKEND_UNSPECIFIED
}

func (x *SnapshotRequest) GetBackendConfig() *BackendConfig {
	if x != nil {
		return x.BackendConfig
	}
	return nil
}

type SnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotResponse) Reset() {
	*x = SnapshotResponse{}
	mi := &file_snapshot_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotResponse) ProtoMessage() {}

func (x *SnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotResponse.ProtoReflect.Descriptor instead.
func (*SnapshotResponse) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{15}
}

func (x *SnapshotResponse) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type RestoreRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// job_id is the unique identifier for the job, unique per agent
	// (group does not namespace job IDs).
	JobId string `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	// group is an optional identifier for a set of related jobs.
	Group string `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	// Deprecated: Use backend_config instead.
	//
	// Deprecated: Marked as deprecated in snapshot_agent.proto.
	Backend Backend `protobuf:"varint,3,opt,name=backend,proto3,enum=snapshot_agent.v1alpha1.Backend" json:"backend,omitempty"`
	// backend_config specifies the backend-specific configuration for the restoration.
	BackendConfig *BackendConfig `protobuf:"bytes,4,opt,name=backend_config,json=backendConfig,proto3" json:"backend_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreRequest) Reset() {
	*x = RestoreRequest{}
	mi := &file_snapshot_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreRequest) ProtoMessage() {}

func (x *RestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreRequest.ProtoReflect.Descriptor instead.
func (*RestoreRequest) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{16}
}

func (x *RestoreRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *RestoreRequest) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

// Deprecated: Marked as deprecated in snapshot_agent.proto.
func (x *RestoreRequest) GetBackend() Backend {
	if x != nil {
		return x.Backend
	}
	return Backend_BACKEND_UNSPECIFIED
}

func (x *RestoreRequest) GetBackendConfig() *BackendConfig {
	if x != nil {
		return x.BackendConfig
	}
	return nil
}

type RestoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreResponse) Reset() {
	*x = RestoreResponse{}
	mi := &file_snapshot_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreResponse) ProtoMessage() {}

func (x *RestoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreResponse.ProtoReflect.Descriptor instead.
func (*RestoreResponse) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{17}
}

func (x *RestoreResponse) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type GetOperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOperationRequest) Reset() {
	*x = GetOperationRequest{}
	mi := &file_snapshot_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperationRequest) ProtoMessage() {}

func (x *GetOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperationRequest.ProtoReflect.Descriptor instead.
func (*GetOperationRequest) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{18}
}

func (x *GetOperationRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type GetOperationResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Status OperationStatus        `protobuf:"varint,1,opt,name=status,proto3,enum=snapshot_agent.v1alpha1.OperationStatus" json:"status,omitempty"`
	// storage_bytes is set on COMPLETE
	StorageBytes *int64 `protobuf:"varint,2,opt,name=storage_bytes,json=storageBytes,proto3,oneof" json:"storage_bytes,omitempty"`
	// snapshot_device_bytes is set on COMPLETE
	SnapshotDeviceBytes *int64 `protobuf:"varint,3,opt,name=snapshot_device_bytes,json=snapshotDeviceBytes,proto3,oneof" json:"snapshot_device_bytes,omitempty"`
	ElapsedMs           int64  `protobuf:"varint,4,opt,name=elapsed_ms,json=elapsedMs,proto3" json:"elapsed_ms,omitempty"`
	// error is set on FAILED
	Error         *string `protobuf:"bytes,5,opt,name=error,proto3,oneof" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOperationResponse) Reset() {
	*x = GetOperationResponse{}
	mi := &file_snapshot_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOperationResponse) ProtoMessage() {}

func (x *GetOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOperationResponse.ProtoReflect.Descriptor instead.
func (*GetOperationResponse) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{19}
}

func (x *GetOperationResponse) GetStatus() OperationStatus {
	if x != nil {
		return x.Status
	}
	return OperationStatus_OPERATION_STATUS_UNSPECIFIED
}

func (x *GetOperationResponse) GetStorageBytes() int64 {
	if x != nil && x.StorageBytes != nil {
		return *x.StorageBytes
	}
	return 0
}

func (x *GetOperationResponse) GetSnapshotDeviceBytes() int64 {
	if x != nil && x.SnapshotDeviceBytes != nil {
		return *x.SnapshotDeviceBytes
	}
	return 0
}

func (x *GetOperationResponse) GetElapsedMs() int64 {
	if x != nil {
		return x.ElapsedMs
	}
	return 0
}

func (x *GetOperationResponse) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_snapshot_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{20}
}

type JobStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	State         JobState               `protobuf:"varint,2,opt,name=state,proto3,enum=snapshot_agent.v1alpha1.JobState" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobStatus) Reset() {
	*x = JobStatus{}
	mi := &file_snapshot_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobStatus) ProtoMessage() {}

func (x *JobStatus) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobStatus.ProtoReflect.Descriptor instead.
func (*JobStatus) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{21}
}

func (x *JobStatus) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobStatus) GetState() JobState {
	if x != nil {
		return x.State
	}
	return JobState_JOB_STATE_UNSPECIFIED
}

type AcceleratorStatus struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MemoryUsedBytes  int64                  `protobuf:"varint,2,opt,name=memory_used_bytes,json=memoryUsedBytes,proto3" json:"memory_used_bytes,omitempty"`
	MemoryTotalBytes int64                  `protobuf:"varint,3,opt,name=memory_total_bytes,json=memoryTotalBytes,proto3" json:"memory_total_bytes,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *AcceleratorStatus) Reset() {
	*x = AcceleratorStatus{}
	mi := &file_snapshot_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcceleratorStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceleratorStatus) ProtoMessage() {}

func (x *AcceleratorStatus) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceleratorStatus.ProtoReflect.Descriptor instead.
func (*AcceleratorStatus) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{22}
}

func (x *AcceleratorStatus) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AcceleratorStatus) GetMemoryUsedBytes() int64 {
	if x != nil {
		return x.MemoryUsedBytes
	}
	return 0
}

func (x *AcceleratorStatus) GetMemoryTotalBytes() int64 {
	if x != nil {
		return x.MemoryTotalBytes
	}
	return 0
}

type StatusResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	JobStatuses         []*JobStatus           `protobuf:"bytes,1,rep,name=job_statuses,json=jobStatuses,proto3" json:"job_statuses,omitempty"`
	AcceleratorStatuses []*AcceleratorStatus   `protobuf:"bytes,2,rep,name=accelerator_statuses,json=acceleratorStatuses,proto3" json:"accelerator_statuses,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_snapshot_agent_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snapshot_agent_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_snapshot_agent_proto_rawDescGZIP(), []int{23}
}

func (x *StatusResponse) GetJobStatuses() []*JobStatus {
	if x != nil {
		return x.JobStatuses
	}
	return nil
}

func (x *StatusResponse) GetAcceleratorStatuses() []*AcceleratorStatus {
	if x != nil {
		return x.AcceleratorStatuses
	}
	return nil
}

var File_snapshot_agent_proto protoreflect.FileDescriptor

const file_snapshot_agent_proto_rawDesc = "" +
	"\n" +
	"\x14snapshot_agent.proto\x12\x17snapshot_agent.v1alpha1\"#\n" +
	"\rProcessTarget\x12\x12\n" +
	"\x04pids\x18\x01 \x03(\x05R\x04pids\"d\n" +
	"\x11CudaBackendConfig\x12O\n" +
	"\x0fexplicit_target\x18\x01 \x01(\v2&.snapshot_agent.v1alpha1.ProcessTargetR\x0eexplicitTarget\"l\n" +
	"\x19DirectMemoryBackendConfig\x12O\n" +
	"\x0fexplicit_target\x18\x01 \x01(\v2&.snapshot_agent.v1alpha1.ProcessTargetR\x0eexplicitTarget\"c\n" +
	"\x10TpuBackendConfig\x12O\n" +
	"\x0fexplicit_target\x18\x01 \x01(\v2&.snapshot_agent.v1alpha1.ProcessTargetR\x0eexplicitTarget\"\xaf\x01\n" +
	"\x11AppEndpointConfig\x12.\n" +
	"\x03app\x18\x01 \x01(\x0e2\x1c.snapshot_agent.v1alpha1.AppR\x03app\x12\x1c\n" +
	"\tendpoints\x18\x02 \x03(\tR\tendpoints\x128\n" +
	"\x04mode\x18\x03 \x01(\x0e2$.snapshot_agent.v1alpha1.SuspendModeR\x04mode\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\"`\n" +
	"\x10AppChannelConfig\x128\n" +
	"\x04mode\x18\x01 \x01(\x0e2$.snapshot_agent.v1alpha1.SuspendModeR\x04mode\x12\x12\n" +
	"\x04tags\x18\x02 \x03(\tR\x04tags\"\x95\x03\n" +
	"\rBackendConfig\x12@\n" +
	"\x04cuda\x18\x01 \x01(\v2*.snapshot_agent.v1alpha1.CudaBackendConfigH\x00R\x04cuda\x12O\n" +
	"\fapp_endpoint\x18\x02 \x01(\v2*.snapshot_agent.v1alpha1.AppEndpointConfigH\x00R\vappEndpoint\x12L\n" +
	"\vapp_channel\x18\x03 \x01(\v2).snapshot_agent.v1alpha1.AppChannelConfigH\x00R\n" +
	"appChannel\x12Y\n" +
	"\rdirect_memory\x18\x04 \x01(\v22.snapshot_agent.v1alpha1.DirectMemoryBackendConfigH\x00R\fdirectMemory\x12=\n" +
	"\x03tpu\x18\x05 \x01(\v2).snapshot_agent.v1alpha1.TpuBackendConfigH\x00R\x03tpuB\t\n" +
	"\abackend\"\xc2\x01\n" +
	"\x14WorkloadCapabilities\x12M\n" +
	"\x0fsupported_modes\x18\x01 \x03(\x0e2$.snapshot_agent.v1alpha1.SuspendModeR\x0esupportedModes\x12G\n" +
	"\fdefault_mode\x18\x02 \x01(\x0e2$.snapshot_agent.v1alpha1.SuspendModeR\vdefaultMode\x12\x12\n" +
	"\x04tags\x18\x03 \x03(\tR\x04tags\"\x92\x01\n" +
	"\x10RegisterWorkload\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12Q\n" +
	"\fcapabilities\x18\x03 \x01(\v2-.snapshot_agent.v1alpha1.WorkloadCapabilitiesR\fcapabilities\"T\n" +
	"\rCommandResult\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x0e\n" +
	"\x02ok\x18\x02 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\xa7\x01\n" +
	"\x0fWorkloadMessage\x12G\n" +
	"\bregister\x18\x01 \x01(\v2).snapshot_agent.v1alpha1.RegisterWorkloadH\x00R\bregister\x12@\n" +
	"\x06result\x18\x02 \x01(\v2&.snapshot_agent.v1alpha1.CommandResultH\x00R\x06resultB\t\n" +
	"\amessage\"_\n" +
	"\x0fSnapshotCommand\x128\n" +
	"\x04mode\x18\x01 \x01(\x0e2$.snapshot_agent.v1alpha1.SuspendModeR\x04mode\x12\x12\n" +
	"\x04tags\x18\x02 \x03(\tR\x04tags\"$\n" +
	"\x0eRestoreCommand\x12\x12\n" +
	"\x04tags\x18\x01 \x03(\tR\x04tags\"\xc5\x01\n" +
	"\fAgentCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12F\n" +
	"\bsnapshot\x18\x02 \x01(\v2(.snapshot_agent.v1alpha1.SnapshotCommandH\x00R\bsnapshot\x12C\n" +
	"\arestore\x18\x03 \x01(\v2'.snapshot_agent.v1alpha1.RestoreCommandH\x00R\arestoreB\t\n" +
	"\acommand\"\xcd\x01\n" +
	"\x0fSnapshotRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12>\n" +
	"\abackend\x18\x03 \x01(\x0e2 .snapshot_agent.v1alpha1.BackendB\x02\x18\x01R\abackend\x12M\n" +
	"\x0ebackend_config\x18\x04 \x01(\v2&.snapshot_agent.v1alpha1.BackendConfigR\rbackendConfig\"5\n" +
	"\x10SnapshotResponse\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\"\xcc\x01\n" +
	"\x0eRestoreRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12>\n" +
	"\abackend\x18\x03 \x01(\x0e2 .snapshot_agent.v1alpha1.BackendB\x02\x18\x01R\abackend\x12M\n" +
	"\x0ebackend_config\x18\x04 \x01(\v2&.snapshot_agent.v1alpha1.BackendConfigR\rbackendConfig\"4\n" +
	"\x0fRestoreResponse\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\"8\n" +
	"\x13GetOperationRequest\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\"\xab\x02\n" +
	"\x14GetOperationResponse\x12@\n" +
	"\x06status\x18\x01 \x01(\x0e2(.snapshot_agent.v1alpha1.OperationStatusR\x06status\x12(\n" +
	"\rstorage_bytes\x18\x02 \x01(\x03H\x00R\fstorageBytes\x88\x01\x01\x127\n" +
	"\x15snapshot_device_bytes\x18\x03 \x01(\x03H\x01R\x13snapshotDeviceBytes\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"elapsed_ms\x18\x04 \x01(\x03R\telapsedMs\x12\x19\n" +
	"\x05error\x18\x05 \x01(\tH\x02R\x05error\x88\x01\x01B\x10\n" +
	"\x0e_storage_bytesB\x18\n" +
	"\x16_snapshot_device_bytesB\b\n" +
	"\x06_error\"\x0f\n" +
	"\rStatusRequest\"[\n" +
	"\tJobStatus\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x127\n" +
	"\x05state\x18\x02 \x01(\x0e2!.snapshot_agent.v1alpha1.JobStateR\x05state\"}\n" +
	"\x11AcceleratorStatus\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12*\n" +
	"\x11memory_used_bytes\x18\x02 \x01(\x03R\x0fmemoryUsedBytes\x12,\n" +
	"\x12memory_total_bytes\x18\x03 \x01(\x03R\x10memoryTotalBytes\"\xb6\x01\n" +
	"\x0eStatusResponse\x12E\n" +
	"\fjob_statuses\x18\x01 \x03(\v2\".snapshot_agent.v1alpha1.JobStatusR\vjobStatuses\x12]\n" +
	"\x14accelerator_statuses\x18\x02 \x03(\v2*.snapshot_agent.v1alpha1.AcceleratorStatusR\x13acceleratorStatuses*8\n" +
	"\aBackend\x12\x17\n" +
	"\x13BACKEND_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fBACKEND_CUDA\x10\x01\x1a\x02\x18\x01*8\n" +
	"\x03App\x12\x13\n" +
	"\x0fAPP_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bAPP_VLLM\x10\x01\x12\x0e\n" +
	"\n" +
	"APP_SGLANG\x10\x02*_\n" +
	"\vSuspendMode\x12\x1c\n" +
	"\x18SUSPEND_MODE_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14SUSPEND_MODE_OFFLOAD\x10\x01\x12\x18\n" +
	"\x14SUSPEND_MODE_DISCARD\x10\x02*\x8d\x01\n" +
	"\x0fOperationStatus\x12 \n" +
	"\x1cOPERATION_STATUS_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18OPERATION_STATUS_PENDING\x10\x01\x12\x1d\n" +
	"\x19OPERATION_STATUS_COMPLETE\x10\x02\x12\x1b\n" +
	"\x17OPERATION_STATUS_FAILED\x10\x03*\x99\x01\n" +
	"\bJobState\x12\x19\n" +
	"\x15JOB_STATE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eJOB_STATE_IDLE\x10\x01\x12\x15\n" +
	"\x11JOB_STATE_RUNNING\x10\x02\x12\x1b\n" +
	"\x17JOB_STATE_TRANSITIONING\x10\x03\x12\x13\n" +
	"\x0fJOB_STATE_SAVED\x10\x04\x12\x15\n" +
	"\x11JOB_STATE_FAULTED\x10\x052\x85\x04\n" +
	"\x14SnapshotAgentService\x12_\n" +
	"\bSnapshot\x12(.snapshot_agent.v1alpha1.SnapshotRequest\x1a).snapshot_agent.v1alpha1.SnapshotResponse\x12\\\n" +
	"\aRestore\x12'.snapshot_agent.v1alpha1.RestoreRequest\x1a(.snapshot_agent.v1alpha1.RestoreResponse\x12k\n" +
	"\fGetOperation\x12,.snapshot_agent.v1alpha1.GetOperationRequest\x1a-.snapshot_agent.v1alpha1.GetOperationResponse\x12Y\n" +
	"\x06Status\x12&.snapshot_agent.v1alpha1.StatusRequest\x1a'.snapshot_agent.v1alpha1.StatusResponse\x12f\n" +
	"\x0fWorkloadChannel\x12(.snapshot_agent.v1alpha1.WorkloadMessage\x1a%.snapshot_agent.v1alpha1.AgentCommand(\x010\x01B\\ZZgithub.com/llm-d-incubation/llm-d-rl-time-slicing/pkg/snapshot-agent/api/v1alpha1;v1alpha1b\x06proto3"

var (
	file_snapshot_agent_proto_rawDescOnce sync.Once
	file_snapshot_agent_proto_rawDescData []byte
)

func file_snapshot_agent_proto_rawDescGZIP() []byte {
	file_snapshot_agent_proto_rawDescOnce.Do(func() {
		file_snapshot_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_snapshot_agent_proto_rawDesc), len(file_snapshot_agent_proto_rawDesc)))
	})
	return file_snapshot_agent_proto_rawDescData
}

var file_snapshot_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_snapshot_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_snapshot_agent_proto_goTypes = []any{
	(Backend)(0),                      // 0: snapshot_agent.v1alpha1.Backend
	(App)(0),                          // 1: snapshot_agent.v1alpha1.App
	(SuspendMode)(0),                  // 2: snapshot_agent.v1alpha1.SuspendMode
	(OperationStatus)(0),              // 3: snapshot_agent.v1alpha1.OperationStatus
	(JobState)(0),                     // 4: snapshot_agent.v1alpha1.JobState
	(*ProcessTarget)(nil),             // 5: snapshot_agent.v1alpha1.ProcessTarget
	(*CudaBackendConfig)(nil),         // 6: snapshot_agent.v1alpha1.CudaBackendConfig
	(*DirectMemoryBackendConfig)(nil), // 7: snapshot_agent.v1alpha1.DirectMemoryBackendConfig
	(*TpuBackendConfig)(nil),          // 8: snapshot_agent.v1alpha1.TpuBackendConfig
	(*AppEndpointConfig)(nil),         // 9: snapshot_agent.v1alpha1.AppEndpointConfig
	(*AppChannelConfig)(nil),          // 10: snapshot_agent.v1alpha1.AppChannelConfig
	(*BackendConfig)(nil),             // 11: snapshot_agent.v1alpha1.BackendConfig
	(*WorkloadCapabilities)(nil),      // 12: snapshot_agent.v1alpha1.WorkloadCapabilities
	(*RegisterWorkload)(nil),          // 13: snapshot_agent.v1alpha1.RegisterWorkload
	(*CommandResult)(nil),             // 14: snapshot_agent.v1alpha1.CommandResult
	(*WorkloadMessage)(nil),           // 15: snapshot_agent.v1alpha1.WorkloadMessage
	(*SnapshotCommand)(nil),           // 16: snapshot_agent.v1alpha1.SnapshotCommand
	(*RestoreCommand)(nil),            // 17: snapshot_agent.v1alpha1.RestoreCommand
	(*AgentCommand)(nil),              // 18: snapshot_agent.v1alpha1.AgentCommand
	(*SnapshotRequest)(nil),           // 19: snapshot_agent.v1alpha1.SnapshotRequest
	(*SnapshotResponse)(nil),          // 20: snapshot_agent.v1alpha1.SnapshotResponse
	(*RestoreRequest)(nil),            // 21: snapshot_agent.v1alpha1.RestoreRequest
	(*RestoreResponse)(nil),           // 22: snapshot_agent.v1alpha1.RestoreResponse
	(*GetOperationRequest)(nil),       // 23: snapshot_agent.v1alpha1.GetOperationRequest
	(*GetOperationResponse)(nil),      // 24: snapshot_agent.v1alpha1.GetOperationResponse
	(*StatusRequest)(nil),             // 25: snapshot_agent.v1alpha1.StatusRequest
	(*JobStatus)(nil),                 // 26: snapshot_agent.v1alpha1.JobStatus
	(*AcceleratorStatus)(nil),         // 27: snapshot_agent.v1alpha1.AcceleratorStatus
	(*StatusResponse)(nil),            // 28: snapshot_agent.v1alpha1.StatusResponse
}
var file_snapshot_agent_proto_depIdxs = []int32{
	5,  // 0: snapshot_agent.v1alpha1.CudaBackendConfig.explicit_target:type_name -> snapshot_agent.v1alpha1.ProcessTarget
	5,  // 1: snapshot_agent.v1alpha1.DirectMemoryBackendConfig.explicit_target:type_name -> snapshot_agent.v1alpha1.ProcessTarget
	5,  // 2: snapshot_agent.v1alpha1.TpuBackendConfig.explicit_target:type_name -> snapshot_agent.v1alpha1.ProcessTarget
	1,  // 3: snapshot_agent.v1alpha1.AppEndpointConfig.app:type_name -> snapshot_agent.v1alpha1.App
	2,  // 4: snapshot_agent.v1alpha1.AppEndpointConfig.mode:type_name -> snapshot_agent.v1alpha1.SuspendMode
	2,  // 5: snapshot_agent.v1alpha1.AppChannelConfig.mode:type_name -> snapshot_agent.v1alpha1.SuspendMode
	6,  // 6: snapshot_agent.v1alpha1.BackendConfig.cuda:type_name -> snapshot_agent.v1alpha1.CudaBackendConfig
	9,  // 7: snapshot_agent.v1alpha1.BackendConfig.app_endpoint:type_name -> snapshot_agent.v1alpha1.AppEndpointConfig
	10, // 8: snapshot_agent.v1alpha1.BackendConfig.app_channel:type_name -> snapshot_agent.v1alpha1.AppChannelConfig
	7,  // 9: snapshot_agent.v1alpha1.BackendConfig.direct_memory:type_name -> snapshot_agent.v1alpha1.DirectMemoryBackendConfig
	8,  // 10: snapshot_agent.v1alpha1.BackendConfig.tpu:type_name -> snapshot_agent.v1alpha1.TpuBackendConfig
	2,  // 11: snapshot_agent.v1alpha1.WorkloadCapabilities.supported_modes:type_name -> snapshot_agent.v1alpha1.SuspendMode
	2,  // 12: snapshot_agent.v1alpha1.WorkloadCapabilities.default_mode:type_name -> snapshot_agent.v1alpha1.SuspendMode
	12, // 13: snapshot_agent.v1alpha1.RegisterWorkload.capabilities:type_name -> snapshot_agent.v1alpha1.WorkloadCapabilities
	13, // 14: snapshot_agent.v1alpha1.WorkloadMessage.register:type_name -> snapshot_agent.v1alpha1.RegisterWorkload
	14, // 15: snapshot_agent.v1alpha1.WorkloadMessage.result:type_name -> snapshot_agent.v1alpha1.CommandResult
	2,  // 16: snapshot_agent.v1alpha1.SnapshotCommand.mode:type_name -> snapshot_agent.v1alpha1.SuspendMode
	16, // 17: snapshot_agent.v1alpha1.AgentCommand.snapshot:type_name -> snapshot_agent.v1alpha1.SnapshotCommand
	17, // 18: snapshot_agent.v1alpha1.AgentCommand.restore:type_name -> snapshot_agent.v1alpha1.RestoreCommand
	0,  // 19: snapshot_agent.v1alpha1.SnapshotRequest.backend:type_name -> snapshot_agent.v1alpha1.Backend
	11, // 20: snapshot_agent.v1alpha1.SnapshotRequest.backend_config:type_name -> snapshot_agent.v1alpha1.BackendConfig
	0,  // 21: snapshot_agent.v1alpha1.RestoreRequest.backend:type_name -> snapshot_agent.v1alpha1.Backend
	11, // 22: snapshot_agent.v1alpha1.RestoreRequest.backend_config:type_name -> snapshot_agent.v1alpha1.BackendConfig
	3,  // 23: snapshot_agent.v1alpha1.GetOperationResponse.status:type_name -> snapshot_agent.v1alpha1.OperationStatus
	4,  // 24: snapshot_agent.v1alpha1.JobStatus.state:type_name -> snapshot_agent.v1alpha1.JobState
	26, // 25: snapshot_agent.v1alpha1.StatusResponse.job_statuses:type_name -> snapshot_agent.v1alpha1.JobStatus
	27, // 26: snapshot_agent.v1alpha1.StatusResponse.accelerator_statuses:type_name -> snapshot_agent.v1alpha1.AcceleratorStatus
	19, // 27: snapshot_agent.v1alpha1.SnapshotAgentService.Snapshot:input_type -> snapshot_agent.v1alpha1.SnapshotRequest
	21, // 28: snapshot_agent.v1alpha1.SnapshotAgentService.Restore:input_type -> snapshot_agent.v1alpha1.RestoreRequest
	23, // 29: snapshot_agent.v1alpha1.SnapshotAgentService.GetOperation:input_type -> snapshot_agent.v1alpha1.GetOperationRequest
	25, // 30: snapshot_agent.v1alpha1.SnapshotAgentService.Status:input_type -> snapshot_agent.v1alpha1.StatusRequest
	15, // 31: snapshot_agent.v1alpha1.SnapshotAgentService.WorkloadChannel:input_type -> snapshot_agent.v1alpha1.WorkloadMessage
	20, // 32: snapshot_agent.v1alpha1.SnapshotAgentService.Snapshot:output_type -> snapshot_agent.v1alpha1.SnapshotResponse
	22, // 33: snapshot_agent.v1alpha1.SnapshotAgentService.Restore:output_type -> snapshot_agent.v1alpha1.RestoreResponse
	24, // 34: snapshot_agent.v1alpha1.SnapshotAgentService.GetOperation:output_type -> snapshot_agent.v1alpha1.GetOperationResponse
	28, // 35: snapshot_agent.v1alpha1.SnapshotAgentService.Status:output_type -> snapshot_agent.v1alpha1.StatusResponse
	18, // 36: snapshot_agent.v1alpha1.SnapshotAgentService.WorkloadChannel:output_type -> snapshot_agent.v1alpha1.AgentCommand
	32, // [32:37] is the sub-list for method output_type
	27, // [27:32] is the sub-list for method input_type
	27, // [27:27] is the sub-list for extension type_name
	27, // [27:27] is the sub-list for extension extendee
	0,  // [0:27] is the sub-list for field type_name
}

func init() { file_snapshot_agent_proto_init() }
func file_snapshot_agent_proto_init() {
	if File_snapshot_agent_proto != nil {
		return
	}
	file_snapshot_agent_proto_msgTypes[6].OneofWrappers = []any{
		(*BackendConfig_Cuda)(nil),
		(*BackendConfig_AppEndpoint)(nil),
		(*BackendConfig_AppChannel)(nil),
		(*BackendConfig_DirectMemory)(nil),
		(*BackendConfig_Tpu)(nil),
	}
	file_snapshot_agent_proto_msgTypes[10].OneofWrappers = []any{
		(*WorkloadMessage_Register)(nil),
		(*WorkloadMessage_Result)(nil),
	}
	file_snapshot_agent_proto_msgTypes[13].OneofWrappers = []any{
		(*AgentCommand_Snapshot)(nil),
		(*AgentCommand_Restore)(nil),
	}
	file_snapshot_agent_proto_msgTypes[19].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_snapshot_agent_proto_rawDesc), len(file_snapshot_agent_proto_rawDesc)),
			NumEnums:      5,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_snapshot_agent_proto_goTypes,
		DependencyIndexes: file_snapshot_agent_proto_depIdxs,
		EnumInfos:         file_snapshot_agent_proto_enumTypes,
		MessageInfos:      file_snapshot_agent_proto_msgTypes,
	}.Build()
	File_snapshot_agent_proto = out.File
	file_snapshot_agent_proto_goTypes = nil
	file_snapshot_agent_proto_depIdxs = nil
}
